### ISSUE TITLE
Include wiki content other than the feature descriptions to the CLDF dataset

### ISSUE THREAD

**Issue by xrotwang** [grambank/grambank#13]
There are a couple of non-feature-description pages in the wiki. Many of these are linked from the feature descriptions and hence should be included in the CLDF dataset. Here's the full list:
```shell
$ la *.md | grep -v GB
Absence-of-evidence.md
Affixes-and-clitics.md
Agreement.md
Background-of-the-Grambank-questionnaire.md
Basics-of-coding-Grambank.md
Coding-conflict-resolution.md
Coding-strategies,-hints-and-suggestions.md
Contribute.md
Core-arguments-(S,-A-and-P).md
Dedicated-marking.md
Encountering-coding-problems-and-solving-them.md
FAQ-(coders).md
FAQ-(general).md
Glossing-abbreviations-used-in-this-wiki.md
Grammatical-gender-and-other-notions-of-gender.md
Home.md
How-we-learn-about-the-languages’-structure-so-that-we-might-code.md
Indexing-vs.-pronouns.md
Interacting-with-experts.md
Language-internal-variation-and-different-strategies-for-one-function.md
List-of-all-features.md
Logical-dependencies-between-features.md
Noun-Classes-and-Classifiers.md
Obligatoriness.md
'on-the-verb-noun'-or-'by-morphology'.md
Particles.md
Productivity.md
Referencing-sources-in-Grambank.md
Relative-Clauses.md
Responsibilities-for-parties-involved-in-Grambank.md
Revising-existing-coding.md
Some-preliminaries-on-typology-in-general-as-it-relates-to-Grambank.md
Submitting-coding-sheets-via-Pull-Requests-(PR).md
Terminology-and-concepts.md
Wordhood-and-phonological-boundness-or-independence.md
```

Linked are these:
```
Relative-Clauses
%27on-the-verb-noun%27-or-%27by-morphology%27
Affixes-and-clitics
Agreement
Core-arguments-(S,-A-and-P)
Dedicated-marking
Grammatical-gender-and-other-notions-of-gender
Indexing-vs.-pronouns
Noun-Classes-and-Classifiers
Obligatoriness
Particles
Productivity
Wordhood-and-phonological-boundness-or-independence
```

**Comment by HedvigS** [comment]
Okay. What does it mean that they are in the CLDF-dataset?

We have the feature descriptions on the website. We have the wiki. I'm not opposed to this, I'm just trying to figure out what is where and why :)

**Comment by HedvigS** [comment]
If these are "published" in some other sense than in the wiki, then that's not what we had been planning for. We were thinking that this would be on the wiki and on that the feature articles would also be on the website. If the rest is also published in another place, we may want to do some further revision with that in mind.

**Comment by xrotwang** [comment]
The github Wiki isn't really anything I'd trust to be around for - say -
another 10 years. So as far as the wiki pages document the coding, I think
it would make sense to include them in the archived dataset that's supposed
to be around for much longer.

Hedvig Skirgård ***@***.***> schrieb am Fr., 11. Juni 2021,
15:29:

**Comment by xrotwang** [comment]
To elaborate: I'd consider the Grambank CLDF dataset - i.e. the package that is going to be uploaded to Zenodo - the only publication of the Grambank data in the academic sense, i.e. as the thing that's
- archived and accessible longterm,
- assigned a DOI (guaranteeing long-term access),
- citeable

There'll also be the paper, and we'll recommend citing both, data and paper when using the data. But neither GitHub wiki nor website at grambank.clld.org is something I'd consider a publication (and in particular it's nothing I'd consider stable for more than 10-15 years). So if we wanted to have the content of these additional pages accessible in the longterm (and I think we should since it's referenced in the other pages), it would need to go into the CLDF dataset.

**Comment by HedvigS** [comment]
Right, okay. In that case maybe we'll need to double check that also the non-feature articles are all to the standard we want right now.

**Comment by HedvigS** [comment]
I've added it to the next patron meeting agenda.

**Comment by HedvigS** [comment]
@jlesg we've talked about this, but I was not sure if everyone has indeed signed off on all the articles. I had a look over and I liked all the current articles. I just need to update the node table in the background article.
