### ISSUE TITLE
giiw1236 not in the release

### ISSUE THREAD

**Issue by alenawitzlack** [grambank/grambank#14]
Dear all,
I am checking whether all the sheets from Kiel which got ever submitted to me made it into the last release. And I see [this submitted sheet](https://github.com/glottobank/Grambank/blob/master/original_sheets/ER_giiw1236.tsv), but it does not show up in [the database](https://grambank.clld.org/languages). Should we be doing something about it?
Alena

**Comment by xrotwang** [comment]
It did make it into the CLDF dataset (https://github.com/glottobank/grambank-cldf/blob/v1.0-rc7/cldf/languages.csv). I don't remember when I last updated the website, though. Will check.

**Comment by alenawitzlack** [comment]
Thanks, I see a few more I was missing on this list, so I assume they are also taken care of.

**Comment by xrotwang** [comment]
Yes, about 300 varieties. I'm running the re-import right now, will let you know when the website is updated.

**Comment by xrotwang** [comment]
Missing data should be online now, see https://grambank.clld.org/languages/giiw1236
