### ISSUE TITLE
[kusa1251] change (delete/merge with [hoav1238]) request

### ISSUE THREAD

**Issue by barlowrussell** [grambank/grambank#17]
The coding for Kusaghe-Njela [kusa1251] cites (exclusively) "Davis 2003 A Grammar of the Hoava Language, Western Solomons". Not only does this source seem to reflect a different language (Hoava [hoav1238]), but this other language is already coded in GB. The coding for "both" languages seems nearly identical, but with some slight differences in the comments.

**Comment by HedvigS** [comment]
[Thanks for your comment @barlowrussell . We've been discussing this over at glottobank/grambank as well and found a resolution.](https://github.com/glottobank/Grambank/issues/1912) 

Just in general, if there is a variation between sub-varieties below the language level we do separate sheets, however, small the difference.

**Comment by HedvigS** [comment]
To recap the discussion over at glottobank/grambank for this public repos:

Nataliia noted:
_kusa1251 is coded based on a grammar for hoav1238: Davis 2003 is a source listed for Hoava on glottolog. The running language name used in the Davis 2003 grammar is also Hoava and not Kusaghe-Njela. Please check._

Hedvig found that Naomi had submitted this to Harald a while ago:
_In regards to Hoava, there is a misclassification in Glottolog. Davis discusses the lack of difference between Hoava and Kusaghe and says they are the same language (2003:8). There is some discussion on how speakers believe they are the same language, and how Tryon and Hackman (1983) misclassified them upon inaccurate data. A single language called 'Hoava-Kusaghe' with three dialects (Hoava, Kusaghe and Njela) is more accurate._

Harald said that this is in a glottolog to do-list: 
_thanks for the sheets and for the explanation re Hoava and Kusaghe. I completely agree with you and I will change the next edition of Glottolog accordingly._

[The matter is currently lying with Harald at Glottolog.](https://github.com/glottolog/glottolog/issues/807)

**Comment by HedvigS** [comment]
I'm going to close this issue here now.
