### ISSUE TITLE
migrating old issues from glottobank/grambank to grambank/grambank

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#2]
All issues tagged for "coding problem", at the very least, should be migrated. I'm checking over what is tagged as what right now.

Is a html solution still the best? I really wish there was a more neat solution, but it sounds okay.

**Comment by HedvigS** [comment]
Okay, I've gone through closed issues which weren't tagged for "coding problem" and tagged a few more as coding problem if it seemed appropriate.

**Comment by SimonGreenhill** [comment]
can this be closed?

**Comment by HedvigS** [comment]
Not sure, I think so? 
this was after discussions with @xrotwang i think.

**Comment by xrotwang** [comment]
The issues have not been migrated here. So if we close, that would mean this won't happen, right?

**Comment by HedvigS** [comment]
Indeed. I can't trace back the discussion, but I think this is something we shouldn't do.

**Comment by xrotwang** [comment]
> but I think this is something we shouldn't do.

shouldn't do what? closing the issue or migrating the issues?

**Comment by HedvigS** [comment]
migrating the issues, we're not doing that anymore right?

**Comment by xrotwang** [comment]
ok, good.
