### ISSUE TITLE
checks failing bc missing file

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#21]
The checks for PRs #20 and #18 are failing and it seems to have to do with a missing file:

`No such file or directory: 'cldf/StructureDataset-metadata.json'`

**Comment by xrotwang** [comment]
Yes, they never succeeded. They will, once the CLDF has been moved here - i.e. upon release of the dataset.

**Comment by HedvigS** [comment]
Okay cool, thanks for explaining that.
