### ISSUE TITLE
make this repos private?

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#24]
I want to trial the issue workflow for coding revision. I'd like to try that in private mode if that's possible.

**Comment by xrotwang** [comment]
But that would make the wiki inaccessible. Can't you trial with a new throwaway repos?

**Comment by HedvigS** [comment]
can we not make all the github users at glottobank/grambank have access to this repos as read?

**Comment by xrotwang** [comment]
possibly. But didn't we advertise the wiki articles elsewhere? E.g. in the preprint?

**Comment by HedvigS** [comment]
No, that's not a thing that I'm aware of at all. In fact, I was always a bit uneasy about this repos being public and have intentionally not given out links to outsiders before release.

**Comment by HedvigS** [comment]
There is a link to the wiki in the preprint, I had actually forgotten about that because I mainly was thinking of the reviewers not the preprint audience.

**Comment by xrotwang** [comment]
Why would the trial require privacy?

**Comment by HedvigS** [comment]
because it may show up on people's pages as activity, leading to more people noticing this repos and I thought we wanted to avoid that before publication.

**Comment by xrotwang** [comment]
I'd find it more irritating if I was lead to the wiki from the preprint and would hit a wall now when there was none last week.

**Comment by HedvigS** [comment]
Okay. I think we'd have to leave it public then.
