### ISSUE TITLE
suggested corrections for 4 Mixtec varieties [first batch]

### ISSUE THREAD

**Issue by SAuderset** [grambank/grambank#25]
* Are you submitting a comment in regards to more than 10 data-points? If so, please complete this form and attach a spreadsheet with columns for feature ID number, language name/glottocode and a comment field. You can find [a blank Grambank coding sheet here](https://github.com/grambank/grambank/blob/master/docs/Grambank_most_updated_sheet.tsv). Please fill in Feature and Language ID for the relevant datapoints. *
Yes, 16 data points so far. Spreadsheet is named gb1_mixtec_corrections1.tsv

* Have you read the Grambank wiki article for the features that you want to suggest a change for? If not, please visit our [wiki](https://github.com/grambank/grambank/wiki) .
 Yes, I read them.

* What language or dialect would you like to suggest a change in coding for? Please give the Name and/or glottocode. (If more than 10 data-points, please just refer to the spreadsheet.)*
concerns 4 languages so far (alac1244, magd1235, sant1436, tezo1238)

* What features do you want to suggest a change for? (If more than 10 data-points, please just refer to the spreadsheet.)*
see gb1_mixtec_corrections1.tsv

* What is the reason behind this change?*
corrections to current coding

* What is your expertise in regards to this language or dialect?*
I do documentation on one Mixtec variety and have experience working with all documented Mixtec varieties from a historical perspective

* What sources do you have in regards to this change in coding?*
 The corrections are based on the same sources as were used originally.

[Archive.zip](https://github.com/grambank/grambank/files/10508573/Archive.zip)

**Comment by yafinka** [comment]
@SAuderset 
A quick qustion regarding GB023 (Are there postnominal articles?) for sant1236.
The examples with the definite article _ma_ are prenominal. Did you find any examples with postnominal _ma_?

**Comment by SAuderset** [comment]
Let me check. That does sound wrong... I'm wondering if I accidentally copied in the wrong feature ID. Sorry about that, will try to get back asap with more info.

**Comment by yafinka** [comment]
No worries and no rush.
All your other suggestions and comments that I've reviewd so far are improvements to Grambank - thank you!

**Comment by HedvigS** [comment]
Here is a list of the Mixtec languages already in Grambank raw (i.e. the continued data after grambank 1.0)

      filename Glottocode                         Name
1:  JE_atat1238   atat1238            Atatláhuca Mixtec
2:  JE_ayut1236   ayut1236                Ayutla Mixtec
3:  JE_coat1241   coat1241            Coatzospan Mixtec
4:  JG_sanm1295   sanm1295  San Miguel El Grande Mixtec
5:  MM_magd1235   magd1235     Magdalena Peñasco Mixtec
6: RHE_alac1244   alac1244         Alacatlatzala Mixtec
7: RHE_sant1436   sant1436 Santa María Zacatepec Mixtec
8: RHE_tezo1238   tezo1238             Tezoatlán Mixtec

**Comment by HedvigS** [comment]
We also have five Mixtec in the to do-list:

These are assigned to @johnaell 
Diuxi-Tilantongo Mixtec | diux1235
Jamiltepec Mixtec | jami1235

These are currently unassigned:
Ocotepec Mixtec | ocot1243
Silacayoapan Mixtec | sila1250
Yosondúa Mixtec | yoso1239

**Comment by SAuderset** [comment]
@yafinka I checked and it is a copy error on my side - oops! so GB023 in my spreadsheet is GB022, or in other words, there are prenominal articles.

**Comment by yafinka** [comment]
Hello @SAuderset!

It took me a while to decide what to code for GB020 (Are there definite or specific articles?) for alac1244 and sanm1244. After consulting with Michael on this one, I decided to code '?' for both, since the deictic function in the examples provided cannot be ruled out. Michael thinks that the function of demonstratives in the Mixtec languages may be evolving under the influence of Spanish.

Do you have any further suggestions for corrections? If not, I will submit the changes and close this issue.

Thanks again for your help!
Olga

**Comment by SAuderset** [comment]
Right now that's all I have. I'm not sure when I will make it through the rest of the features, so probably best to close it. Thanks!

**Comment by yafinka** [comment]
I submitted the changes to the code yesterday. Thank you everyone!
