### ISSUE TITLE
active coders contributors here

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#26]
I'm going to need [all active coders](https://github.com/glottobank/Grambank/blob/master/CONTRIBUTORS.md) to be added to this repos so I can assign them issues. For example, I need to assign Olga to #25

**Comment by xrotwang** [comment]
There seem to be a couple of email addresses in the `GitHub-username` column.

**Comment by xrotwang** [comment]
all invited

**Comment by HedvigS** [comment]
> There seem to be a couple of email addresses in the `GitHub-username` column.

Okay, I'll see if I can sort that out.

thanks!

**Comment by HedvigS** [comment]
Is it the case that @johnaell has been invited but not accepted?

**Comment by xrotwang** [comment]
I'd guess so. The invitation isn't pending anymore, though, so would need to be resent.

**Comment by HedvigS** [comment]
Okay. Could you please do so?

Or give me admin privliges such that I can invite people, resend invites etc.

**Comment by xrotwang** [comment]
Your admin now.

**Comment by HedvigS** [comment]
@xrotwang ich danke dir 🙏
