### ISSUE TITLE
access management

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#3]
@xrotwang can you please give @hjhaynie @jlesg @alenawitzlack @jaylatarche writing access to this repos? They're editing the wiki.

I would also appreciate more editing rights, and I suspect so would @SimonGreenhill

**Comment by HedvigS** [comment]
@SimonGreenhill do you have any higher permissions than me, i.e. can give me higher permissions?

**Comment by SimonGreenhill** [comment]
no, I don't think I have higher permissions. Do these people need them, as I think it's good if the content gets reviewed via the PR framework (helps catch typos etc at the very least!)

**Comment by xrotwang** [comment]
As far as I can tell, all patrons should have received invitations to this repos, including sufficient permssions to edit the wiki.

**Comment by HedvigS** [comment]
@xrotwang Okay, thanks Robert. I will ask them to double check this then.
Can I have permissions such that I can add and adjust permissions?

**Comment by HedvigS** [comment]
@SimonGreenhill for wiki edits the PR workflow doesn't really work as far as I know. I tried to research it a while ago but I couldn't figure it out easily. If you know how I'm sure everyone would be happy to try it.

**Comment by HedvigS** [comment]
To be entirely clear, all of us patrons are going through a final review of all features to make them as clear as possible to outsiders. We've set up a peer reviewing system (you'll notice because of issues at glottobank/grambank) and we're expecting to be entirely done first week of September. This won't affect the revisions fixing, which we're hoping will be finished end of august.

**Comment by HedvigS** [comment]
@xrotwang Can you invite @Jaylatarche again? Thank you for your patience.

**Comment by xrotwang** [comment]
done

**Comment by HedvigS** [comment]
Many thanks.

**Comment by HedvigS** [comment]
@xrotwang 

@JeremyCollinsMPI also needs access to editing wiki and says he currently does not have it.

**Comment by xrotwang** [comment]
@JeremyCollinsMPI should have received an invitation from github, which he needs to accept to gain write access.

**Comment by HedvigS** [comment]
I'll remind him of this.
