### ISSUE TITLE
inclusive / exclusive, Japhug

### ISSUE THREAD

**Issue by rgyalrong** [grambank/grambank#32]
Concerning: the feature "[Is there a distinction between inclusive and exclusive?](https://grambank.clld.org/parameters/GB028)" about the language Japhug japh1234:
https://grambank.clld.org/valuesets/GB028-japh1234
The value should be 0.

There is no incl/excl distinction in Japhug, the source cited (Jacques 2004: 340) contains a comparative table of Rgyalrong languages, and all other languages do have incl/excl (Situ, Zbu, Tshobdun), but this contrast was lost in Japhug.

**Comment by HedvigS** [comment]
Thank you @rgyalrong for opening this issue! A coder will be assigned to you shortly.

**Comment by Grace-ph** [comment]
Hello @rgyalrong, I have made this revision for Japhug and will be submitting it today. Thank you for being our first revision submitted since publication!
