### ISSUE TITLE
The remaining features for Modern Hebrew (hebr1245): GB027, GB105, GB136, GB158, GB159, GB160, and GB298

### ISSUE THREAD

**Issue by ran-arigur** [grambank/grambank#34]
> Are you submitting a comment in regards to more than 10 data-points?

I am not.

> Have you read the Grambank wiki article for the features that you want to suggest a change for?

I have.

> What features do you want to suggest a change for?

* [GB027](https://grambank.clld.org/parameters/GB027) ("Are nominal conjunction and comitative expressed by different elements?")
* [GB105](https://grambank.clld.org/parameters/GB105) ("Can the recipient in a ditransitive construction be marked like the monotransitive patient?")
* [GB136](https://grambank.clld.org/parameters/GB136) ("Is the order of core argument (i.e. S/A/P) constituents fixed?")
* [GB158](https://grambank.clld.org/parameters/GB158) ("Are verbs reduplicated?")
* [GB159](https://grambank.clld.org/parameters/GB159) ("Are nouns reduplicated?")
* [GB160](https://grambank.clld.org/parameters/GB160) ("Are elements apart from verbs or nouns reduplicated?")
* [GB298](https://grambank.clld.org/parameters/GB298) ("Can standard negation be marked by an inflecting word ('auxiliary verb')?")

> What language or dialect would you like to suggest a change in coding for? Please give the Name and/or glottocode.
> Are there particular languages or dialects of concern? Please give the name(s) and/or glottocode(s).

Modern Hebrew (hebr1245)

> What is the reason behind this change?

This language is currently coded as '?' for these features.

> What is your expertise in regards to this feature/language(s)?

I speak the language reasonably well. That said, I couldn't confidently code some of these features without reference to a source.

> What sources do you have in regards to this change in coding?

Glinert, Lewis. *The grammar of Modern Hebrew*. Cambridge University Press, 2004. (Note: the source itself is from 1989, but I have the paperback printing from 2004; so it should only be considered up-to-date as of 1989, but I give the date as 2004 because that's what my page numbers refer to.)

Additionally, I used [the Even-Shoshan Dictionary](https://en.wikipedia.org/wiki/Even-Shoshan_Dictionary) to look up etymologies of various words and see whether they're Modern coinages or inherited from older forms of the language. That is: Even-Shoshan, Abraham. הַמִּלּוֹן הֶחָדָשׁ [The New Dictionary]. Kiryat-Sefer Ltd., 1984.

---

**[GB027](https://grambank.clld.org/parameters/GB027)** ("Are nominal conjunction and comitative expressed by different elements?")

This feature should be coded as '1'. NP coordination uses the coordinator *ve-*; the comitative uses the preposition *im*.

For NP coordination, see Glinert 2004 pages 383&ndash;386 (and elsewhere). The source explicitly identifies *ve-* as a coordinator meaning "and", and discusses its uses in coordinating NPs as well as many other kinds of phrases and clauses. The use of plural agreement with a coordinated noun phrase (whose coordinates are each singular) is mentioned in various places, including page 386.

For the comitative . . . Glinert 2004 doesn't use the exact word "comitative" anywhere, but there are various example sentences that use *im* as a comitative, including on page 151 ("leH **im** d&aacute;ni" glossed as "Go **with** Danny").

There are also some examples implicitly contrasting the coordinator *ve-* and the preposition *im*; for example, pages 387&ndash;388 discuss how the verb *hitnashek* ("kissed") can take either a coordinated subject ("&eacute;li ve-&eacute;ster hitnashku shuv", "Eli and Esther kissed again" &mdash; the verb has plural agreement) or an object with *im* ("&eacute;li hitnashek im &eacute;ster", "Eli kissed with Esther" &mdash; the verb has singular agreement), among other possibilities.

---

**[GB105](https://grambank.clld.org/parameters/GB105)** ("Can the recipient in a ditransitive construction be marked like the monotransitive patient?")

This feature should be coded as '1', with a comment that this is the case for the verb *limed* "teach". That verb takes two direct objects (meaning two objects that each use the preposition *et* if definite, or no preposition if indefinite): one for the theme, one for the addressee. The same is *not* true of the other verbs mentioned in the feature description; most of those use a direct object for the theme and a different preposition for the recipient/addressee.

See Glinert 2004 page 163, which mentions *limed* "teach", *sha'al* "ask (a question)", and *heevir* "take..across (the road etc.)" as "the only common *et...et...* verbs".

---

**[GB136](https://grambank.clld.org/parameters/GB136)** ("Is the order of core argument (i.e. S/A/P) constituents fixed?")

This feature should be coded as '0'. Although Glinert 2004 mentions a special intonation used in "casual Hebrew" when preposing an object to mark it as the topic, it goes on to mention that in "more formal usage" there are circumstances where topic-preposing is more general and does *not* require special intonation.

See Glinert 2004 pages 416&ndash;417, which gives various examples of VS, VOS, and OVS word order for discourse purposes in formal Hebrew (as opposed to the default SVO); page 416 mentions the "no need for the rise-fall tone".

---

**[GB158](https://grambank.clld.org/parameters/GB158)** ("Are verbs reduplicated?")

I'm not sure how to proceed with this one.

As far as I can find, Glinert 2004 mentions verb-based reduplication in two places:

* page 460: "Another method [of creating a secondary root from an existing root] is to reduplicate the final root consonant of a verb or noun"; two of the four examples are ones where the base word is a verb (namely *irbev* "to mix" from *erev* "to involve", and *ofef* "to fly" from *af* "to fly"). An endnote adds that "Several two-consonant roots are of this type" (that is, the type of *af*&rarr;*ofef*).
    * This part doesn't explicitly discuss the productivity of reduplicating a verb in this way, though it *does* mention that "*Noun*-based roots as a whole are productively coined today" [emphasis mine]. So that seems to be an implicit suggestion of *non*-productivity.
    * I find in Even-Shoshan 1984 that both of his verb-based examples are ancient words that are inherited by Modern Hebrew.
    * I spent some time checking Even-Shoshan 1984 for various other words that came to mind that seemed potentially relevant, and most of them (*sovev*, *soHeaH*, *hitpotsets*, *Himem*, *hitkarer*, *hitmoded*, *hit'oshesh*, *romem*, *hitbarer*, *hitbonen*, *hitpalel*, *hitrotsets*, *hitkonen*) turned out to be ancient as well. The only example I thought of that did turn out to be Modern was *sifrer* ("to number"; from *safar* "to count").
* page 489 says that adjectives formed by reduplication are "*mostly* from unsuffixed adjectives" [emphasis mine], but one of the examples is from a verb (*hafaHfaH* "fickle" from *hafaH* "to change"). Consulting Even-Shoshan 1984 again, I find that that example is another ancient word.

My personal feeling (not specifically supported by Glinert 2004) is that all of these examples are lexicalized, and so the feature should be coded as '0'. The *ofef* pattern seems to have been productive in an older form of the language, but I don't think it's making new words today; and even if we find more examples like *irbev* and *sifrer*, I think they'd be one-offs without an overall pattern in their meaning &mdash; nothing like the example of Leti on the feature page, where reduplication productively derives instrument nouns.

---

**[GB159](https://grambank.clld.org/parameters/GB159)** ("Are nouns reduplicated?")

I think this feature should be coded as '1'; there are a few diminutive nouns formed from other nouns by reduplicating the last syllable (plus vowel changes), and Glinert 2004 says of this pattern that "there are 10-15 common examples, reasonably productive" (page 433).

This isn't as clear-cut as some of the features above &mdash; both "productive" and "lexicalized" seem subjective &mdash; but since the source explicitly calls this "reasonably productive", I assume we want to err on the side of accepting that judgment?

---

**[GB160](https://grambank.clld.org/parameters/GB160)** ("Are elements apart from verbs or nouns reduplicated?")

Similarly to the previous, I think this feature should be coded as '1'; there are a number of diminutive adjectives (and a few augmentative adjectives) formed from other adjectives by reduplicating the last syllable (plus vowel changes), and Glinert 2004 describes this/them as "not numerous but fairly productive" (page 489).

---

**[GB298](https://grambank.clld.org/parameters/GB298)** ("Can standard negation be marked by an inflecting word ('auxiliary verb')?")

I believe this should be coded as '1', because one way to mark negation is with the negator *en*, which (in this sense) inflects to agree with a preceding subject in person, gender, and number. This is not the most common negator &mdash; for one thing, it's restricted to the present tense, and mostly restricted to formal Hebrew &mdash; but I think it still counts as a grammatical marking of standard negation.

See Glinert 2004 pages 293&ndash;297, which explains this, and gives examples such as *hu eno mevashel* glossed as "he not + SUFF cooks" and hence "He does not cook".

---

Please let me know if you have any questions to clarify any of the above, and I'll do my best to answer them.

**Comment by JanisReimringer** [comment]
Dear @ran-arigur ,

thank you for your detailed description of the issue and the listing of the sources.  I assigned myself to the task and will get back to you as soon as I have revised the features or if there are any follow-up questions.

**Comment by JanisReimringer** [comment]
Dear @ran-arigur,

I have completed checking all of the features in question and, after consulting the corresponding sources and our Grambank resources, I have coded the features according to your suggestions. I will submit the revision today. Thank you for your very insightful comments and for doing the research necessary to become familiar with the Grambank features.

**Comment by ran-arigur** [comment]
Thanks, @JanisReimringer!

But I'm a bit confused &mdash; I don't see any relevant commits to this project (at https://github.com/grambank/grambank/commits/master), and https://grambank.clld.org/languages/hebr1245 still shows question marks for these features. Can you double-check that your revision went through?

**Comment by JanisReimringer** [comment]
Dear @ran-arigur,

thank you for asking! The revision went through but the changes are made in a different repository, I should have mentioned that. They will be available on grambank/grambank for the public with the next Grambank release. 

You can have a look at the hebr1245 sheet here with the latest corrections: 
[NB_hebr1245.csv](https://github.com/grambank/grambank/files/11778451/NB_hebr1245.csv)

**Comment by ran-arigur** [comment]
@JanisReimringer : Ah, understood. Thanks again!
