### ISSUE TITLE
Corrections to Siwi (siwi1239)

### ISSUE THREAD

**Issue by lameens** [grambank/grambank#37]
* Are you submitting a comment in regards to more than 10 data-points? If so, please complete this form and attach a spreadsheet with columns for feature ID number, language name/glottocode and a comment field. You can find [a blank Grambank coding sheet here](https://github.com/grambank/grambank/blob/master/docs/Grambank_most_updated_sheet.tsv). Please fill in Feature and Language ID for the relevant datapoints.  The file needs to be zipped in order to be attached to an issue.*
Yes; attached: [Grambank_most_updated_sheet-siwi-corrections.csv](https://github.com/grambank/grambank/files/11465482/Grambank_most_updated_sheet-siwi-corrections.csv) For features that I consider to already be correctly coded, I have left the value blank.

* Have you read the Grambank wiki article for the features that you want to suggest a change for? If not, please visit our [wiki](https://github.com/grambank/grambank/wiki) .
Yes, I have (in most cases).

* What features do you want to suggest a change for? (If more than 10 data-points, please just refer to the spreadsheet.)*
See spreadsheet, comments below. The proposed changes concern a total of 37 data-points.

* What language or dialect would you like to suggest a change in coding for? Please give the Name and/or glottocode. (If more than 10 data-points, please just refer to the spreadsheet.)*
Siwi (siwi1239)

* What is the reason behind this change?*
Some of the features values are incorrect (even just relative to the source cited), and some of the comments are wrong or misplaced, or deserve further elaboration.

* What is your expertise in regards to this feature/language(s)?*
I have done months of in situ fieldwork on Siwi, and wrote one of the two references used for it in GramBank.

* What sources do you have in regards to this change in coding?*
Those already cited, plus the following:
Souag, Lameen. 2013. Berber and Arabic in Siwa (Egypt): A Study in Linguistic Contact.  Berber Studies Vol. 37. Köln: Rüdiger Köppe.
Souag, Lameen. 2014. The Development of Dative Agreement in Berber: Beyond Nominal Hierarchies“. Transactions of the Philological Society 113:2, pp. 213-248, 2015. https://halshs.archives-ouvertes.fr/halshs-01376203/document .
Souag, Lameen. Unpublished ms. Siwi lexicon.

The proposed changes may be seen as needing more elaboration, especially since several of them are based on the same sources already cited. To provide clarity, more specific comments by feature are given below:

GB025	What is the order of adnominal demonstrative and noun?	1	Vycichl 2005: 198	Demonstrative prefixes.

This should have been encoded as 0; adnominal demonstratives very consistently follow the noun. The citation refers to a situation hypothesised by Vycichl to hold for pre-proto-Berber, not to present-day Siwi, where the noun prefixes are not demonstratives of any kind. Vycichl’s synchronic description is confusing on this point, but his examples of adnominal demonstratives in context consistently follow the noun (2005:223); for more explicit statements confirming their invariably postnominal position, cf. Souag (2010:261-263; 2013:146).

GB041	Are there several nouns (more than three) which are suppletive for number?	0	Vycichl 2005: 198-206	There are masculine and feminine plural suffixes and Arabic irregular/internal plural forms. The irregular plurals are not considered suppletive, because their root consonants remain the same.

This should be changed to 1. The source cited gives precisely three nouns which are suppletive for number (Vycichl 2005:203): ‘bread’, ‘son’, and ‘foot’. Souag (2013:64) also gives three: ‘foot’, ‘sister’, and ‘bedding’ (the first two are also in Souag 2010:80). Combining both sets yields five, thus changing the correct coding to 1. (From a purely synchronic perspective, other nouns could also have been added, e.g. ‘brother’.)

GB042	Is there productive overt morphological singular marking on nouns?	0	Vycichl 2005: 198-199	

This should have been encoded as 1; an explicit statement to this effect may be absent, but cp. the examples in Vycichl 2005:200-207, and compare e.g. Souag 2013:91. Most nouns in Siwi feature a noun class prefix which marks gender and number; the prefix a-/ta- reliably indicates singular number, and is frequently added even to Arabic loanwords.

GB059	Is the adnominal possessive construction different for alienable and inalienable nouns?	0	Souag 2010: 1-519

This should have been encoded as 1, based on Souag 2010:307 as well as Vycichl 2005:219, Souag 2013:162.

GB071	Are there morphological cases for pronominal core arguments (i.e. S/A/P)?	1	Vycichl 2005: 216

This should have been encoded as 0, based on the stated criteria and the source cited (which agrees in this respect with all other sources). The case-marked forms are phonologically bound, and “This question is about phonologically independent pronouns only; indexes are irrelevant”.

GB072	Are there morphological cases for oblique non-pronominal NPs (i.e. not S/A/P)?	1	Vycichl 2005: 208	Dative case is formed with the preposition i- (y-/ye-).

The encoding is consistent with the source cited, and as such is defensible. Note, however, that I analyse this preposition as a separate word (Souag 2010:308; 2013:163). Neither I nor Vycichl present arguments for our respective positions, so this could motivate encoding it as ?. In the absence of clearly stated criteria for distinguishing proclitics from short words, answers to this question are likely to be inconsistent not only cross-linguistically but across different sources for the same language.

GB083	Is there overt morphological marking on the verb dedicated to past tense?	1	Vycichl 2005: 226, 230

While the coding is consistent with the source’s preferred label, it should be corrected to 0. What Vycichl labels “past tense”, in accordance with the terminological habits of his generation, is more correctly analysed by Comrie’s standards as aspect, as seen both by its use with stative verbs for present time reference (see Souag 2010:385, 2013:193-194) and by the possibility of using Vycichl’s “present” with past time reference (see Souag 2010:386-387, 2013:194-195).

GB084	Is there overt morphological marking on the verb dedicated to future tense?	1	Vycichl 2005: 229	

As far as I can tell from the rather ambiguous wording of the description (“It can be hard to distinguish future tense from different modal categories”), this should be corrected to 0 for the same reasons as with GB083. Siwi has no dedicated future tense marker; ga- is best described as an irrealis marker (Souag 2010: 382-383), used in a wide range of contexts including but not limited to future tense reference.

GB099	Can verb stems alter according to the person of a core participant?	0	Vycichl 2005: 1-258	Using the root and pattern system, there is no strong suppletion as long as the root consonants remain the same.

There is indeed no strong suppletion, but weak suppletion (i.e. synchronically unproductive alternations) conditioned by person is seen in the verbs ‘go’ and ‘come’ (Vycichl 2005:237-238). ‘Go’ has the stem ṛaḥ in 3sg/1pl vs. ḥḥ in 1/2sg and 3pl; ‘come’ has the stem usəd in 3sg/1pl vs. us in 1/2sg and 3pl. So, according to the guidelines, this is encoded correctly, but should have a comment.

GB103	Is there a benefactive applicative marker on the verb (including indexing)?	0	Souag 2010: 1-519	

This should be encoded as 1, since “datives/benefactives are marked through
apparently obligatory dative pronominal affixes on the verb stem”; cf. Souag 2010:311, Souag 2013:165.

GB105	Can the recipient in a ditransitive construction be marked like the monotransitive patient?	0	Souag 2010: 311	Recipients/benefactives take the prepositional dative marker i.

This is correctly encoded based on the source, but further data reveals that some ditransitive verbs, e.g. ‘teach (by memorisation)’, do allow the recipient to be encoded without i, yielding a double object construction; see Souag 2015:236 (“The development of dative agreement in Berber”).

GB113	Are there verbal affixes or clitics that turn intransitive verbs into transitive ones?	?	Vycichl 2005: 1-258	Not discussed.

Should be coded 1. There is a highly productive causative prefix s-; see Souag 2010:359, 2013:177 (and indeed Vycichl 2005:239 passim).

GB114	Is there a phonologically bound reflexive marker on the verb?	?	Vycichl 2005: 1-258	Not discussed.

Should be coded 0; not discussed, but examples using the reflexive pronoun may be found in Souag 2013:247, 258; for a partial paradigm of the reflexive pronoun, see Vycichl 2005:221.

GB115	Is there a phonologically bound reciprocal marker on the verb?	?	Vycichl 2005: 1-258	Not discussed.

Not discussed in available sources, but should be coded 0 (personal observation).

GB123	Are there verb-adjunct (aka light-verb) constructions?	0	Souag 2010: 1-519	

This accurately describes the source referred to, but in the light of subsequent evidence should be changed to 1; Siwi turns out to have a limited number of expressions that fit the definition given for light verbs, e.g. əṃṃəl yəṭ, lit. ‘say yəṭ’, for ‘gleam’ (Souag, unpublished lexicon).

GB138	Can standard negation be marked clause-initially?	1	Souag 2010: 436	

This should be coded as 0 according to steps 5-7 of the criteria provided; since Siwi default word order is SVO, and negation directly precedes the verb, clause-initial negation only occurs as a result of argument omission, with presumably pragmatically marked VS order, or (as in the only example on p. 436) in imperatives.

GB159	Are nouns reduplicated?	1	Souag 2010: 184	Sometimes, numbers are reduplicated to form ordinal numbers.

Surely numbers (and quantifiers) are not nouns? Unless they are deemed to count as such, this should be coded as 0 or as ? (personally, I would go for ? - I suspect that nouns can be reduplicated in distributive uses, but I can’t find any for the moment).

GB204	Do collective ('all') and distributive ('every') universal quantifiers differ in their forms or their syntactic positions?	0	Vycichl 2005: 223	

This should be encoded as 1; cf. Souag 2010:196-197. Vycichl 2005:223 misleadingly glosses kul as “every, all”, which would be accurate for Arabic but is not accurate for Siwi.

GB250	Can predicative possession be expressed with a transitive 'habeo' verb?	0	Souag 2010: 236	Predicative possession is formed with the existential plus dative pronoun. Not explicitly mentioned; inferred from examples.

The encoding is correct, but the comment is not; ɣuṛ- is a preposition ‘at, chez’, not an existential, and there is no dative pronoun.

GB252	Can predicative possession be expressed with an S-like possessum and a locative-coded possessor?	0	Souag 2010: 236	Predicative possession is formed with the existential plus dative pronoun. Not explicitly mentioned; inferred from examples.

This should be encoded as 1; see discussion for GB250.

GB254	Can predicative possession be expressed with an S-like possessum and a possessor that is coded like an adnominal possessor?	0	Souag 2010: 236	Predicative possession is formed with the existential plus dative pronoun. Not explicitly mentioned; inferred from examples.

This should be encoded as 0; see discussion for GB250.

GB256	Can predicative possession be expressed with an S-like possessor and a possessum that is coded like a comitative argument?	0	Souag 2010: 236	Predicative possession is formed with the existential plus dative pronoun. Not explicitly mentioned; inferred from examples.
The comment is incorrect; see discussion for GB250.

GB263	Is there a clause-final polar interrogative particle?	1	Souag 2010: 452	The last vowel of a sentence is lengthened to form a question.

The coding is correct, but the comment should rather note that “ na ula “or no?” may be placed finally as a question tag”.

GB273	Is there a comparative construction with a standard marker that elsewhere has neither a locational meaning nor a 'surpass/exceed' meaning?	0	Souag 2010: 159	

This should have been encoded with 1; the standard marker is genitive n, as indicated in the source cited.

GB275	Is there a bound comparative degree marker on the property word in a comparative construction?	0	Vycichl 2005: 212	

The property word is typically marked using non-concatenative pattern morphology, as the source already makes clear; does that not count as “bound”? If it does (the criteria are not explicit on this point), this should be coded as 1.

GB276	Is there a non-bound comparative degree marker modifying the property word in a comparative construction?	1	Vycichl 2005: 212	

The coding is correct, in that some adjectives cannot take the pattern morphology discussed in GB275, but Vycichl 2005: 212 says nothing about this; for examples with a phonologically free marker, see rather Souag 2010:160-161.

GB300	Does the verb for 'give' have suppletive verb forms?	1	Souag 2010: 42	

This should be encoded as 0, according to the guidelines, since the stem form variation referred to in the source happens to be weak suppletion, not strong suppletion. See Souag 2013:51-52.

GB306	Is there a phonologically independent non-bipartite reciprocal pronoun?	0	Souag 2010: 1-519	

The source does not address this question, so the coding was procedurally correct; it should, however, be changed to 1 (Souag ms), since Siwi uses ajar-sən “between-3PL” to mean “each other”, e.g. yəẓṛina ajar-sən “they saw each other”, itərrafən af ajarsən “they fear each other”.

GB309	Are there multiple past or multiple future tenses, distinguishing distance from Time of Reference?	1	Vycichl 2005: 230	

This should have been encoded as 0. Vycichl’s distinction between the “past” (i.e. perfective) and the “present past” (i.e. perfect/resultative) has nothing to do with distance from Time of Reference.

GB314	Can augmentative meaning be expressed productively by a shift of gender/noun class?	1	Souag 2010: 61	

This should have been encoded as 0; I explicitly state (p. 66) that the process is not productive in Siwi.

GB315	Can diminutive meaning be expressed productively by a shift of gender/noun class?	1	Vycichl 2005: 199	

This should have been encoded as 0; the process is not productive in Siwi (Souag 2010:66), and Vycichl already calls it “rather rare”.

GB334	Is there synchronic evidence for any element of a quinary numeral system?	0	Vycichl 2005: 213-215

This encoding is correct for normal numerals. However, it should perhaps be noted that Siwi also has a secondary system of cryptic/argot numerals using base 5 (Souag 2010:185, 2013:112).

**Comment by lameens** [comment]
PS: Looking at Egyptian Arabic and Maltese, I notice that the expression of comparative degree through pattern morphology has consistently been marked as 0 for GB275, i.e. as not constituting a bound comparative degree marker. I find this very strange - what could possibly be more tightly bound than non-concatenative pattern morphology? - but if it's consistent across the project, then I suppose it should be applied here too. If so, however, could this please be made explicit in the description provided at https://grambank.clld.org/parameters/GB275#2/21.0/151.9 , and/or in the wiki page [[Wordhood and phonological boundness or independence]]?

**Comment by jlesg** [comment]
Hi @lameens , thank you for your feedback and for your corrections! Someone will soon assign themselves to do some checks and integrate the changes in Grambank.

I want to briefly address your comment on pattern morphology and bound markers. What triggers a 0 with pattern morphology is not that it is not bound, but that it is not a 'marker', at least not in the sense we use it in Grambank (currently, this is only explicit on the page on [affixes and clitics](https://github.com/grambank/grambank/wiki/Affixes-and-clitics), so perhaps we should also make that explicit elsewhere - so thank you for pointing out that it's not clear in the feature description). If the question were whether there's (bound) morphology, pattern morphology would definitely trigger a 1, as you suggest.

**Comment by lameens** [comment]
Hi @jlesg, thanks for your comment! If that's the sense of marker you use here, OK.

Since the sheet needs updating anyway in light of that, I think I'll add answers to the remaining questions, and correct a couple more I had missed first time around. Here's the updated version:
[Grambank_most_updated_sheet-siwi-corrections2.csv](https://github.com/grambank/grambank/files/11470494/Grambank_most_updated_sheet-siwi-corrections2.csv)

And here are the corresponding comments:
GB021	Do indefinite nominals commonly have indefinite articles?	0	Vycichl 2005: 196	

This accurately encodes the source as cited, although Vycichl 2005:178 contrarily suggests that stress alternations code (in)definiteness. Subsequent work tends to confirm the latter suggestion, indicating that this should be coded as 1; indefiniteness is marked by final stress according to the analysis of Souag 2010:119-121, 2013:80-82. The question is complicated, however, by the difficulty of deciding which form is unmarked.

GB043	Is there productive morphological dual marking on nouns?	1	Vycichl 2005: 198	Dual can only be marked on certain Arabic loan words.

Should have been encoded as 0 according to the criteria given; as the comment already makes clear, this dual marking cannot be considered productive. In fact, the dual is restricted to a subset of measure nouns; cf. Souag 2010:186-188, 2013:113-115.

GB119	Can mood be marked by an inflecting word ("auxiliary verb")?
No; encode as 0.

GB120	Can aspect be marked by an inflecting word ("auxiliary verb")?
No; encode as 0.

GB121	Can tense be marked by an inflecting word ("auxiliary verb")?
No; encode as 0.

GB400	Are all person categories neutralized in some voice, tense, aspect, mood and/or negation?	Alena Witzlack-Makarevich	1507	
No, so encode as 0.

GB401	Is there a class of patient-labile verbs?	Alena Witzlack-Makarevich	841	
Yes, so encode as 1; see Souag 2010:360, Souag 2013:177.

GB402	Does the verb for 'see' have suppletive verb forms?	Hedvig Skirgård	1128	
Encode as 0; no suppletive verb forms.

GB403	Does the verb for 'come' have suppletive verb forms?	Hedvig Skirgård	1157	
Encode as 1; suppletive imperative hed (vs. us/usəd).

GB408	Is there any accusative alignment of flagging?	Alena Witzlack-Makarevich	1772	
There is never any overt argument flagging; encode as 0.

GB409	Is there any ergative alignment of flagging?	Alena Witzlack-Makarevich	1769	
There is never any overt argument flagging; encode as 0.

GB410	Is there any neutral alignment of flagging?	Alena Witzlack-Makarevich	1743	
There is never any overt argument flagging; encode as 1.

GB415	Is there a politeness distinction in 2nd person forms?	Hannah J. Haynie	1739	
No; code as 0.

GB421	Is there a preposed complementizer in complements of verbs of thinking and/or knowing?	Hedvig Skirgård	1111	
Yes (although it’s optional), so encode as 1; cf. Souag 2010:466-467, 2013:223.

GB422	Is there a postposed complementizer in complements of verbs of thinking and/or knowing?	Hedvig Skirgård	1120	
No, so encode as 0; cf. Souag 2010:466-467, 2013:223.

GB430	Can adnominal possession be marked by a prefix on the possessor?	Hannah J. Haynie	1853	
Encode as 0. The question is arguable, but both Souag and Vycichl transcribe the genitive preposition as a separate word; cf. Vycichl 2005:207-208, Souag 2010:307, 2013:162.

GB431	Can adnominal possession be marked by a prefix on the possessed noun?	Hannah J. Haynie	1865	
No; code as 0. Cf. Vycichl 2005:207-208, Souag 2010:307, 2013:162.

GB432	Can adnominal possession be marked by a suffix on the possessor?	Hannah J. Haynie	1851	
No; code as 0. Cf. Vycichl 2005:207-208, Souag 2010:307, 2013:162.

GB433	Can adnominal possession be marked by a suffix on the possessed noun?	Hannah J. Haynie	1872	
Yes, for inalienable nouns only; encode as 1. Cf. Vycichl 2005:218-219, Souag 2010:307, 2013:162.

GB519	Can mood be marked by a non-inflecting word ("auxiliary particle")?	Hedvig Skirgård	1601	
No; encode as 0.

GB520	Can aspect be marked by a non-inflecting word ("auxiliary particle")?	Hedvig Skirgård	1663	
There is a progressive adverb ʕammal (Souag 2010:374, 2013:183), but its usage is not obligatory; encode as 0.

GB521	Can tense be marked by a non-inflecting word ("auxiliary particle")?	Hedvig Skirgård	1696	
There is a past tense adverb maṛṛa (cf. Souag 2010:374, 2013:183), but its usage is not obligatory; encode as 0.

GB522	Can the S or A argument be omitted from a pragmatically unmarked clause when the referent is inferrable from context ("pro-drop" or "null anaphora")?
Yes, routinely; encode as 1.

**Comment by lameens** [comment]
A side comment regarding <a href="https://grambank.clld.org/parameters/GB120#2/21.0/151.9">GB120</a>: I deduce both from the chosen examples and from the fact that languages such as Latin are coded as 0 that this is not intended to cover, for instance, inceptive aspect ("begin to X"), but I don't see any explicit wording that would exclude such cases. Perhaps this would be worth clarifying in the text? Or am I missing something?

**Comment by JanisReimringer** [comment]
Hi @lameens, 

thank you for your feedback! 

I just assigned myself to the task. I will get back to you as soon as I have read through your comments and had a chance to check and revise the corresponding features.

**Comment by JanisReimringer** [comment]
> inceptive aspect

First of all, thank you for your question. 

GB120 asks specifically for aspect marking using auxiliary verbs. I have looked into inceptive/inchoative aspect in Latin. According to Väänänen (1981:136-137), inchoative aspect is morphologically marked on the verb with suffix '-sc-'. There is no auxiliary verb involved, which would mean a 0 for GB120.

**Comment by lameens** [comment]
Thank you for your reply. But on what basis are constructions like Latin incipio+X[infinitive] "begin to X" excluded?

**Comment by lameens** [comment]
(My question is not purely general, of course; if verbs like "begin (to)" are counted as aspectual auxiliaries, then Siwi as well as Latin should be coded 1, rather than the 0 that I put above.)

**Comment by JanisReimringer** [comment]
Okay, now I understand your question better. I did not know about this alternative construction before. 

In the specific case of Latin, I would argue that the morphological marker '-sc-' is the dedicated, productive and obligatory (i.e. the most dominant way of expressing the concept) marker for inchoative aspect. 

With the incipio+X[infinitive] construction, it is possible to express the meaning "begin to X" lexically, but such constructions, to my understanding, do not count as grammatical markers of aspect for Grambank. 

@HedvigS, would you agree with me here?

**Comment by lameens** [comment]
The two have somewhat different meanings; -sc- is primarily <a href="https://clt.uab.cat/publicacions_clt/State_Change_of_State_Latin.pdf">change of state</a> (another sense of the term "inchoative"), while incipio expresses the idea of beginning to do something. My Latin is pretty rusty, but I don't think "dormire incipis" (you begin to sleep) is perfectly interchangeable with dormisces "you fall asleep"; still less can optare incipiant "they (should) begin to seek" be replaced by the unattested *optascent (whose nonexistence, alongside that of many others, calls into question the idea that -sc- is "productive and obligatory".) But I guess the broader question is whether a purely aspectual verb like "begin" can ever be treated as lexical in the first place.

**Comment by HedvigS** [comment]
Thanks @JanisReimringer and @lameens 

In regards to the broader question, it's not the case that all verbs meaning "to begin" qualify as aspectual auxiliaries in grambank. We want them to be there essentially [every-time the meaning is invoked](https://github.com/grambank/grambank/wiki/Obligatoriness), not just optionally sometimes when the speaker wants to be less ambitious. This can be tricky to determine in some grammatical descriptions, and this general principle is one of the reasons we go back and re-evaluate old coding. I'm happy to review Latin again, but for now in this thread let's stick to Siwi.

**Comment by JanisReimringer** [comment]
Thank you @HedvigS for your answer.

I wanted to give a quick update to @lameens regarding the revision of Siwi. I have worked through all your comments and suggestions and made the corresponding changes. Thank you for including all of the source references, that was very helpful.

The revised sheet will be uploaded as soon as I have cleared up the question regarding [GB275](https://github.com/grambank/Grambank/wiki/GB275) about non-concatenative marking and after I have another look at inchoative aspect marking in Siwi regarding [GB120](https://github.com/grambank/Grambank/wiki/GB120).

**Comment by lameens** [comment]
Thank you both!

@HedvigS: I'm still not really clear on the definition of an aspectual auxiliary in grambank; given that English "he began to eat" doesn't mean the same thing as "he ate", I don't see why we wouldn't conclude that "begin" is present every time the inceptive meaning is invoked, except in the sense that other near-synonymous choices ("start", "get", etc.) happen to be available. My intuition would be that aspectual auxiliaries count as such by virtue of their position in a paradigm, but that notion doesn't seem to be invoked in the definition. Pending further clarification, though, I'm happy to code it as 0.

@JanisReimringer: The question regarding GB275 seems to have been cleared up by @jlesg upthread - apparently, by the definition used in the project, pattern morphology does not count as a "marker", so GB275 should indeed be coded as 0 for Siwi.

**Comment by HedvigS** [comment]
> @HedvigS: I'm still not really clear on the definition of an aspectual auxiliary in grambank; given that English "he began to eat" doesn't mean the same thing as "he ate", I don't see why we wouldn't conclude that "begin" is present every time the inceptive meaning is invoked, except in the sense that other near-synonymous choices ("start", "get", etc.) happen to be available. My intuition would be that aspectual auxiliaries count as such by virtue of their position in a paradigm, but that notion doesn't seem to be invoked in the definition. Pending further clarification, though, I'm happy to code it as 0.
> 

For us, being in a paradigm is not enough. We're concerned with wether it is necessarily there when the meaning is invoked. Sometimes if we have border-line cases we code "?".

**Comment by lameens** [comment]
Rather than Latin or Siwi, maybe it's more useful to take an example from a language we all share. In English, standard terminology is that "have" (+past-ptcp) is an auxiliary, and "finish" (+pres-ptcp) isn't. But I don't see that "have" is necessarily there when the meaning is invoked - in many contexts where a present perfect is used, you could easily substitute a plain -ed past. Nor am I confident that "finish" can be absent when its meaning is invoked: "I finished eating" does not mean the same thing as "I ate" or even "I stopped eating". I have similar issues with trying to apply this criterion to TAM systems in any other language I know; I can't even imagine how I would go about applying it to one I only knew about from someone else's reference grammar. Do you have something a bit more concrete to draw on?

**Comment by HedvigS** [comment]
There is a gray area here, I agree. Usually in cases where we are uncertain like this we either 1) go by what the grammar writer has said. If they've said that it's obligatory or in other ways labelled it with terms that imply this, we go with that or we 2) leave it as "?". This is a tricky area, indeed.

**Comment by lameens** [comment]
OK. In that case it's probably least misleading if I just leave GB119-GB121 and GB519-GB521 unfilled for Siwi, as they currently are. Here's a spreadsheet updated accordingly.

[Grambank_most_updated_sheet-siwi-corrections3.csv](https://github.com/grambank/grambank/files/11661464/Grambank_most_updated_sheet-siwi-corrections3.csv)

**Comment by HedvigS** [comment]
Thanks for your patience and understanding @lameens . I think @JanisReimringer can take it from here.

**Comment by JanisReimringer** [comment]
Thank you @HedvigS and @lameens!

I have finished revising the siwi1239 sheet and uploaded it, so you will soon be able to have a look at it. In some cases, e.g., with GB119-121 and GB519-521 I've read your arguments and the sources and based my coding decisions trying to balance between Grambank rules and your expertise. 

I am always open to feedback, should there be any follow-up questions.

**Comment by lameens** [comment]
OK, thanks. I can't see it at the moment, so please let me know when it comes online.

**Comment by HedvigS** [comment]
@lameens we haven't set a publication date of version 2.0 yet I'm afraid. @JanisReimringer could you attach the sheet here please?

**Comment by JanisReimringer** [comment]
@HedvigS 

Of course, here is the sheet: [NB_siwi1239_corrections.csv](https://github.com/grambank/grambank/files/11679142/NB_siwi1239_corrections.csv)

@lameens I was upcoding siwi1239 based on an older sheet, the feature questions may be phrased differently. You can navigate the sheet best looking at the feature IDs.

**Comment by lameens** [comment]
Thanks. I'll have a look. For the moment, just a cosmetic point - could you do a search-and-replace to correct "Lameed" and "Soaug" to "Lameen" and "Souag" respectively?

**Comment by JanisReimringer** [comment]
I apologize for the typos! I have corrected the sheet accordingly, here it is: 
[NB_siwi1239_corrections.csv](https://github.com/grambank/grambank/files/11681109/NB_siwi1239_corrections.csv)

**Comment by JanisReimringer** [comment]
I made some further corrections regarding citations. Here is the final version:

[NB_siwi1239.csv](https://github.com/grambank/grambank/files/11770135/NB_siwi1239.csv)
