### ISSUE TITLE
Polish feature revisions

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#39]
Came in via email:

 Hello,

Today, while browsing the Grambank database, I have noticed that Polish has been classified as exhibiting a marker for sensory evidentiality in feature BG322. I decided to check the source, and unfortunately page 180 of Swan's grammar doesn't seem to report anything even remotely resembling evidentiality. The neighboring feature BG323 has some actual evidence supporting it on page 408, but I doubt the distinction between "że" and "czy" differs that much from e.g. English  "that" vs "if/whether" or Russian "что" vs "ли". I would like suggesting that someone take a look at these two and possibly correct them.

Kind regards,
Diego Ostoja-Kowalski

**Comment by Jaylatarche** [comment]
Hiya @HedvigS,

Thank you Diego Ostoja-Kowalski for spotting this!

I have had a look through the grammar and can confirm that this is an incorrect coding. 

On page 180 I cannot see any mention of evidentiality. The page is focused on the usage of adjectives and pronouns and about comparison, identification etc. On page 408, the examples mainly discuss "że" and "czy" after reporting verbs; there doesn’t seem to be any grammatical markers in the authors' discussions or examples that mark evidentiality. 

I'll go ahead and correct this coding to 0 in the sheet.
