### ISSUE TITLE
Belarusian feature change

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#40]
Came in via email:

The coding of Belarusian [bela1254] for feature GB116 (Do verbs classify the shape, size or consistency of absolutive arguments by means of incorporated nouns, verbal affixes or suppletive verb stems?)
should be changed from
"present"
to
absent ("absent" or "Not known")
because
The feature is not mentioned and is likely a clerical error for another feature (description matches zero copula distribution)
as stated in
gByrilaBelaruskaja especially the citation for p106

I have read the feature description at https://grambank.clld.org/parameters/GB116.
My expertise in regards to this language or dialect is master of linguistics with slavistics at SPbGU

Kind regards,
Milenović Milan

**Comment by hojucha** [comment]
Yes, we noticed this mistake last year and corrected it. I believe the changes will take place in the next release of Grambank.

**Comment by HedvigS** [comment]
Yes, I thought this might be the case. I'll get back to Milenović
