### ISSUE TITLE
German, Spanish and Urdu Data Missing

### ISSUE THREAD

**Issue by jjdelvalle** [grambank/grambank#41]
Just a general question regarding data for these languages. Are there plans on adding them to Grambank? I went over the documentation and publications and there is no mention why they weren't included. Any insight into this or why they're missing?

**Comment by HedvigS** [comment]
Hello! Thank you for your question.

Spanish, German and Urdu are coming. We haven't been focussing on Indo-European languages for our research until lately, so they didn't make it into the first release but will most likely be in future releases.

We've got 2.430 languages in the first release, and there are 3.500-4.000 languages in the world that have at least a grammar sketch (i.e could be included). We're working on it ;)!

**Comment by jumelet** [comment]
Dear Hedvig, is there a timeline on these languages? I was quite surprised to see that such high-resource languages are missing (given the MPI is in Germany as well :-)).

I might have a go at Spanish, German, and Afrikaans myself; is it possible for external researchers to contribute new languages to the database?

**Comment by HedvigS** [comment]
Hi @jumelet . I'm sorry, we don't have a set time-line. We are continuously doing work to add, there are many languages in v2 that aren't in V1, including all that you mention. 

To clarify, we do not prioritise languages based on the descriptive material available. We prioritise languages given our research projects. 

We get the question about Spanish and German so often I've added it to a FAQ :) https://github.com/grambank/grambank/wiki/FAQ-(general)#why-isnt-spanishgermanother-language-in-grambank

I will discuss with the project leader Russell Gray regarding external contribution.

**Comment by jumelet** [comment]
Hi Hedvig, thanks for the quick response! That sounds great, I'll just be patient for v2 then :)
