### ISSUE TITLE
Ideophones in Mandarin and other Sinitic languages

### ISSUE THREAD

**Issue by simazhi** [grambank/grambank#42]
* For feature GB296 on ideophones, the value for Mandarin (glottocode mand1415) is "not mentioned". However, I published a whole database, called the Chinese Ideophone Database (CHIDEOD) devoted to this topic. 

[Link to the article](https://brill.com/view/journals/clao/49/2/article-p136_2.xml)

doi: [10.1163/19606028-bja10006](https://doi.org/10.1163/19606028-bja10006)

These were also the topic of [my dissertation (2020)](https://www.thomasvanhoey.com/files/DISSERTATION.pdf)

* For Yue Chinese (glottocode yuec1235) you can look at Mok (2001) and  Bodomo (2006).

Mok, Waiching Enid. 2001. Chinese sound symbolism: A phonological perspective. Hawai’i: University of Hawai’i PhD dissertation.

Bodomo, Adams. 2006. The structure of ideophones in African and Asian languages: The case of Dagaare and Cantonese. In John Mugane, John P. Hutchison & Dee A. Worman (eds.), Selected Proceedings of the 35th Annual Conference on African Linguistics, 203–213. Somerville, MA: Cascadilla Proceedings Project.

* For Hakka Chinese (glottocode hakk1236) you can look at Mok (2001)

Mok, Waiching Enid. 2001. Chinese sound symbolism: A phonological perspective. Hawai’i: University of Hawai’i PhD dissertation.

* For Taibei Hokkien (glottocode taib1242) there are ideophone like constructions such as ABB (see Chang 2009)

Chang, Yufen. 2009. The phonology of ABB reduplication in Taiwanese. In Yun Xiao (ed.), Proceedings of the 21st North American Conference on Chinese Linguistics (NACCL-21): Vol. 1, 28–41. Smithfield, Rhode Island: Bryant University.

* For Gan (I don't think it's in the sample) you can check out Wu (2014).

Wu, Mengqi. 2014. The structure of ideophones in Southern Sinitic. Hong Kong: University of Hong Kong Master thesis.

**The main point is: all Sinitic languages that stem from Old Chinese have ideophones.** 

* What is the reason behind this change?*

Values in the database are "unknown ?" but should be "present"

* What is your expertise in regards to this feature/language(s)?*

7 years of study including a PhD dissertation and a postdoc

* What sources do you have in regards to this change in coding?*

See above

**Comment by HedvigS** [comment]
Thank you @simazhi for your message. We'll assign someone shortly.

Just to note, when we write "not mentioned" it is in specific relation to the sources cited. In this case, we didn't look beyond some larger reference works. We'll remedy that by looking at the sources you suggest.

**Comment by simazhi** [comment]
Hi @HedvigS ! Perfect.

Once again I also want to say, congrats on this great resource. It's gonna come in handy.

**Comment by HedvigS** [comment]
Thanks for helping make it better @simazhi !

**Comment by JanisReimringer** [comment]
Dear @simazhi,

thank you for your detailed input and the listing of the sources and the CHIDEOD database. 

I assigned myself to the task, changed the values accordingly and added the sources you provided for Yue Chinese, Hakka Chinese and Taibei Hokkien. GB296 for Gan was already coded '1'.

Thank you for your help!
