### ISSUE TITLE
some suggestions for the 'Karok' page

### ISSUE THREAD

**Issue by elangokumaran** [grambank/grambank#43]
* Are you submitting a comment in regards to more than 10 data-points? If so, please complete this form and attach a spreadsheet with columns for feature ID number, language name/glottocode and a comment field. You can find [a blank Grambank coding sheet here](https://github.com/grambank/grambank/blob/master/docs/Grambank_most_updated_sheet.tsv). Please fill in Feature and Language ID for the relevant datapoints.  The file needs to be zipped in order to be attached to an issue.*

I have exactly 10 comments, so I guess I won't use the spreadsheet.

* Have you read the Grambank wiki article for the features that you want to suggest a change for? If not, please visit our [wiki](https://github.com/grambank/grambank/wiki) .

yes

* What features do you want to suggest a change for? (If more than 10 data-points, please just refer to the spreadsheet.)*

- The standard modern spelling for the language's name is 'Karuk'. See e.g. Bright and Gehr's (2005) 'Karuk dictionary' and recent UC Berkeley dissertations by Sandy (2017) and Maier (2022), a.m.o.

- GB024: What is the order of numeral and noun in the NP? I think the value should be changed from ? to 1. For instance, see here for examples with 'two' (it seems to me that in the few examples where the numeral does not precede the noun, the numeral is not in fact contained in the NP): https://linguistics.berkeley.edu/~karuk/karuk-dictionary.php?display-mode=g&lx=axak&text-examples=yes&ge=&sd=&pos=&audio=&index-position=&lxGroup-id=864&index-order=&include-derivatives=&display-derivatives=

- GB084: Is there overt morphological marking on the verb dedicated to future tense? I think the value should be changed from 1 to 0. The suffix that Bright decribes as a future marker is actually a prospective aspect marker. Source: Begay [Carpenter], Kayla. 2014. Aspectual Future in Karuk. Ms., UC Berkeley.

- GB086: Is a morphological distinction between perfective and imperfective aspect available on verbs? I think the value should be changed from 0 to 1. See Bright 1957:139 (specifically case 3)).

- GB089, GB091, and GB093. I think the values should be changed from 0 to 1. I think the optional plural suffix -naa qualifies as an index (Bright 1957:112).

- GB109: Is there verb suppletion for participant number? I think the value should be changed from 0 to 1. See Bright 1957:88. More examples with strong suppletion for PL can be found in Bright's dictionary section, e.g. 'run' (Bright 1957:436), 'swim' (Bright 1957:443). I should note, though, that these verb alternations don't seem to be strictly speaking conditioned by morphosyntactic number features. See Garrett and Maier (2022; 'How to do things with birds', UC Berkeley handout): "We suggest that suppletive “dual” and “plural” verbs do not index argument number per se. Roughly, “dual” verbs indicate paired entities or the like; “plural” verbs indicate collective entities or the like." But in this respect, Karuk is not much different, as I understand it, than e.g. Choctaw, which is nonetheless coded as 1 for this feature.

- GB139: Is there a difference between imperative (prohibitive) and declarative negation constructions? I think the value should be changed from 0 to 1. Prohibition is expressed using a preverbal marker xay(faat) and 'positive indicative' agreement morphology ('personal morphemes') (Bright 1957:61, see also 139), whereas declarative negation uses the negative proclitic pu= and 'negative indicative' agreement morphology (Bright 1957:61).

- GB304: Can the agent be expressed overtly in a passive clause? I think this should be changed from 1 to 0 (or ?). Karuk doesn't have a passive, as far as I know. (There is a construction which Bright refers to as the 'special passive', but this construction does not qualify as a passive for our purposes here, since the P argument is not promoted to S status.) Other features related to the passive are coded as ? with the comment 'No clear examples'. I don't know why this feature is coded differently.

- GB409: Is there any ergative alignment of flagging? I think the value should be changed from 0 to 1. The obviative postposition 'îin can flag A but not S or P. Source: Macaulay, Monica. 2000. Obviative Marking in Ergative Contexts: The Case of Karuk 'îin. International Journal of American Linguistics 66.4.

- GB522: Can the S or A argument be omitted from a pragmatically unmarked clause when the referent is inferrable from context ("pro-drop" or "null anaphora")? The value should be changed from ? to 1. See e.g. Bright 1957:119.

* What language or dialect would you like to suggest a change in coding for? Please give the Name and/or glottocode. (If more than 10 data-points, please just refer to the spreadsheet.)*

Karok

* Are there particular languages or dialects of concern? Please give the name(s) and/or glottocode(s). (If more than 10 data-points, please just refer to the spreadsheet.)*

Karok

* What is the reason behind this change?*

improvement

* What is your expertise in regards to this feature/language(s)?*

I'm just an interested linguistics grad student. I don't have any first-hand knowledge of the language.

* What sources do you have in regards to this change in coding?*

see above

**Comment by HedvigS** [comment]
Thank you @elangokumaran ! We will assign someone to look this over.

Regarding the language name, we use the name as found over at glottolog. Please submit an issue about the name here: https://github.com/glottolog/glottolog/issues and the editors there will get on it :)

**Comment by elangokumaran** [comment]
ok thanks!

**Comment by HedvigS** [comment]
@JacobMenschel has been assigned!

**Comment by JacobMenschel** [comment]
Dear @elangokumaran, 
I have looked at your proposals, and I conclude that basically all of them align with what I would code for these features. Here are some comments:
- GB024: I agree that this is clearly a 1. 
- GB084: Sounds right.
- GB086: Yes.
- GB089, GB091, GB093: This is a 1 for those three features too, since as you said the morpheme indexes the number of an argument. However, this would also mean that GB090, GB092 and GB094 are 1 since there seems to be a prefixal allomorph of that plural index. Cf. Bright (1957: 113).
- GB109: Could you provide Garrett and Maier (2022)? I will check with the others how they have coded this feature in these cases. If Choctaw is coded as 1 for this feature, that's already a good hint. But I would understand the reasoning behind either 0 or 1, so I will discuss this with other coders.
- GB139: Agreed.
- GB304: I would assume this is coded 1 due to the example given in Bright (1957: 59), where 'by-his-mother he-is-seen' suggests a passive construction. Nevertheless, I agree that since there is no typical promotion of O, and while there are passive translations, this should be a 0.
- GB409: Yes, this should be a 1. While only used when both arguments are animate, the feature only asks whether there is any ergative flagging at all — hence this should be a 1.
- GB522: Generally, I agree that this should be a 1. It would be useful to see whether there are restrictions on this phenomenon in Karuk: can only 3rd person S/A arguments be dropped? Is it restricted to certain verbs? This is definitely a 1, but if there are any restrictions, I would include them in a comment.

All the best,
Jacob

**Comment by elangokumaran** [comment]
Thanks for looking this over!

- I agree that GB090, GB092, GB094 are 1, but they're already coded as 1, so there's no issue

- Here's Garrett and Maier 2022: [garrett-maier_how-to-do-things-with-birds.pdf](https://github.com/grambank/grambank/files/12071766/garrett-maier_how-to-do-things-with-birds.pdf)

- There are no restrictions on argument omission, as far as I know. See e.g. sentences 4. and 5. here: https://linguistics.berkeley.edu/~karuk/karuk-dictionary.php?display-mode=g&lx=&text-examples=yes&ge=give&sd=&pos=&audio=&index-position=&lxGroup-id=249&index-order=&include-derivatives=&display-derivatives=

**Comment by JacobMenschel** [comment]
Oops, my bad then! Thank you for the paper. I will include your proposals in the coding of Karuk tomorrow then. Thank you again!

**Comment by HedvigS** [comment]
Hi @JacobMenschel and @elangokumaran . Is all resolved here now?

**Comment by JacobMenschel** [comment]
As for my part, yes, I have changed the coding accordingly.

**Comment by HedvigS** [comment]
@elangokumaran you satisfied?

**Comment by elangokumaran** [comment]
Yes, thank you!

**Comment by HedvigS** [comment]
lovely, thanks everyone!
