### ISSUE TITLE
Italian plurals

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#45]
Matt McLauchlin <matt.w.mclau@gmail.com> wrote to us over email:

> Hello there, I've spent some time reading your fascinating site.
> 
> 
> 
> I may have found an error in one of the data points, although I'm not sure if I've understood the property correctly. Feature GB039: Is there nonphonological allomorphy of noun number markers? for Italian is coded "no." However, I was able to think of several cases (a small number of nouns, but very frequent ones, including several body parts) in which the plural marker is irregular, i.e. unpredictable. The normal paradigm is:
> 
> 
> 
> masculine: o/io/e/a -> i (uccello->uccelli; bacio->baci; stivale->stivali; problema->problemi)
> feminine: a -> e (donna->donne); e -> i (nazione->nazioni)
> Nouns ending in a consonant, i, or stressed vowel remain the same, as do abbreviations: bar->bar; crisi->crisi; città->città; foto (abbreviation of fotografia) ->foto.
> 
> 
> Irregular forms include:
> 
> uomo "man" -> uomini
> dio "god" -> dei
> uovo "egg" -> uova
> braccio "arm" -> braccia
> ciglio "eyelash" -> ciglia
> dito "finger" -> dita. Note that uovo, braccio, ciglio, and dito are masculine nouns but their plurals are feminine.
> 
> 
> 
> In some cases, there are different plural forms based on meaning. For example, grido "cry," a masculine noun, has the feminine plural "gride" when referring to human cries/shouts, but the regular masculine plural "gridi" when referring to animal sounds. Dito "finger," a masculine noun, has the feminine plural "dite" usually, but the regular masculine plural "diti" if the fingers are specified (e.g. diti medi "middle fingers"). Muro "wall," a masculine noun, has the feminine plural "mura" when referring to city walls but the regular masculine plural "muri" when referring to house walls. The common plural of ginocchio "knee" is the feminine "ginocchia," but the regular masculine "ginocchi" also exists.
> 
> 
> 
> There are also a few slighter exceptions; for example, most masculine nouns ending in -co /ko/ have the plural -chi /ki/, e.g. succo->succhi, but some have the plural in -ci /tʃi/, e.g. amico->amici.
> 
> 
> 
> I hope I've correctly understood this marker and, if so, that this is helpful to the project!

@Michael90EVAMPI would you be able to look this over please?

**Comment by Michael90EVAMPI** [comment]
Back then I rated those nouns as being not productive enough to trigger a 1. The given examples clearly emerge from the coincidence of Latin declension classes. I know these nouns, but did not have them in mind when coding. On Monday I will start with this issue and will use my fresh head to think it all through again.

**Comment by Michael90EVAMPI** [comment]
Thinking it through it all makes sense. Should I just change it in the sheet adding a comment?

**Comment by HedvigS** [comment]
> Thinking it through it all makes sense. Should I just change it in the sheet adding a comment?

yes please! Feel free to add Matt McLauchlin as a source in the comment.

**Comment by Michael90EVAMPI** [comment]
Done!

**Comment by HedvigS** [comment]
Marvelous! I've informed Matt.

He also said: 

> My pleasure,  thank you! Also, there was a typo in my email, I gave both "dite" and "dita" as irregular plurals of "dito". Only "dita" is correct.
