### ISSUE TITLE
Articles in Vietnamese

### ISSUE THREAD

**Issue by OlenaShcherbakova** [grambank/grambank#49]
It seems that the comments (and maybe values?) for Vietnamese (viet1252) on GB020 (definite) and GB021 (indefinite) have been exchanged.
Namely, the comment for **definite** articles includes: "**Indefinites** are accompanied by a classifier (Vuong and Moore, 1994:103) though I was unable to infer whether these can be deemed as **indefinite articles** as such (see Wiki)"

**Comment by HedvigS** [comment]
@JacobMenschel how'd you feel about assisting @OlenaShcherbakova in more article reviews?

**Comment by JacobMenschel** [comment]
Sure thing! I will be somewhat unavailable the latter half of this week and next week, but I'll try to get it done before! 
@OlenaShcherbakova I will look at your two open issues ( #48 and #49 ) later today!

Best

**Comment by JacobMenschel** [comment]
I agree with your findings, I have fixed the coding accordingly. Thanks!
