### ISSUE TITLE
Derivational benefactive marker in Boano?

### ISSUE THREAD

**Issue by leahpappas** [grambank/grambank#51]
GB103: Can a verb have a benefactive marker (applicative marker or index)?

In Boano there is a derivational affix -i that attaches to nouns and can derive transitive verbs with a benefactive meaning. The base noun indicates the object being given. Two examples include:

_ogo_ ‘water’ + _-i_ = _ogo-i_ ‘to give water’
_latap_ ‘oil’ + _-i_ = _latap-i_ ‘to give/add oil’

Because the derived form is a verb, could -i feasibly be considered a benefactive marker even though it has a derivational function?There is also a ditransitive benefactive construction in Boano, in which both the patient and recipient are unmarked and thus coded as objects. 

_Isin     membeanan  iyaku durian_ 
3SG    give               1SG    durian
‘He gives me durian.’

So in a way, the affix -i might be considered detransitivizing as well, since the patient is no longer an object of the verb. However, there are no examples of this morpheme in a clausal context, so coding needs to rely on examples such as those above.

These particular examples come from Inghuong (1987: 63, 67-68, 97) found at this [link](https://drive.google.com/file/d/1eDMr8ArqXGcm1ZwgEepJoWLnijvgVkAp/view?usp=sharing).

**Comment by jlesg** [comment]
Hi Leah, thanks for your question. That's a fun example!

Since the base that the marker attaches to is not a verb but a noun, this situation should not trigger a 1 for Grambank.  But it'd be really nice if you can add this as a comment.
