### ISSUE TITLE
GB030 moco1246

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#53]
* Have you read the Grambank wiki article for the features that you want to suggest a change for? If not, please visit our [wiki](https://github.com/grambank/grambank/wiki) .

Yes!

* What features do you want to suggest a change for? (If more than 10 data-points, please just refer to the spreadsheet.)*
GB030

* What language or dialect would you like to suggest a change in coding for? Please give the Name and/or glottocode. (If more than 10 data-points, please just refer to the spreadsheet.)*
moco1246

* What is the reason behind this change?*
The coder hasn't considered demonstratives as third person pronouns

* What is your expertise in regards to this feature/language(s)?*
Cristian knows a lot about languages in this area.

* What sources do you have in regards to this change in coding?*
Veronica Grondan 1998

**Comment by yafinka** [comment]
Cristian is right - GB030 should be changed to 1. I submitted the changes, the issue can be closed.
