### ISSUE TITLE
English "ago" and "on" as postpositions

### ISSUE THREAD

**Issue by rmalouf** [grambank/grambank#54]
For feature [GB075: Are there postpositions?](https://grambank.clld.org/parameters/GB075#2/39.6/69.4), English is listed type `0 = no postpositions`. However, _ago_ as in _two years ago_ and _on_ as in _two years on_ sure seem like postpositions, exactly parallel to _in_ (_in two years_) or _after_ (_after two years_). Grambank cites Huddleston & Pullum pgs 602, 603 as its source but on pg 632, H & P write (boldface added):

> Etymologically, _ago_ derives from a past participle form _agone_ (the prefix _a-_ + the past participle of _go_), so that _ten years ago_ has its origin in a subject-predicate construction comparable to that in [17ii] except that the past participle is active rather than passive. _Ago_ is of course no longer construed as a past participle, but how the construction should now be analysed is unclear: it is syntactically highly exceptional. [...] Traditional grammar classifies _ago_ as an adverb, but on the basis that it takes a complement **we analyse it as a preposition, in accordance with the criteria given in §2.4**. It is even more exceptional than _notwithstanding_, etc., in that **it always follows its complement**. _On_, in the sense it has in [18b], namely “later”, likewise cannot occur without the accompanying phrase [...]. We again take the dependent to be a complement, therefore, and treat _on_ in this sense like _ago_, as a **preposition that follows its complement**.

H & P also mention a some more marginal cases (e.g., _all the world over_). I would think this would qualify Standard English, and maybe some of the other English varieties, as type `1 = has postpositions` languages. If it doesn't, it might be helpful to add a comment about why it doesn't to the wiki. That would make it easier for future users to understand the coding criteria.

**Comment by jlesg** [comment]
Hi @rmalouf, thank you for your comment!

I'm the 'patron' for this feature, so responsible for its interpretation. I thought about this for a bit after you posted it and had a look at the data. I agree that English should qualify as 1 for this feature - the fact that these items should be analyzed as taking complements means that they should be analyzed as adpositions.

Changes are made and will be implemented in the next version of Grambank.

Thank you again for the correction!

Jakob
