### ISSUE TITLE
Morelos Nahuatl Feature GB117

### ISSUE THREAD

**Issue by Maunus** [grambank/grambank#55]
My grammar sketch on Hueyapan Nahuatl (Hansen 2017:166) is cited for "Morelos Nahuatl" having a copula verb with nominal predicates. But what I say on the cited page is the opposite, that the particle ka is _not_ a copula verb, that it is not a verb, but a particle that is optionally used to signal that the following noun is a predicate (a kind of focus construction). Nahuatl (also Tetelcingo Nahuatl, and all other Nahua varieties that I know of) notoriously lack copula verbs with nominal predicates.

**Comment by HedvigS** [comment]
@jaimerafaelms or @mariana-pr would you be able to take this?

**Comment by mariana-pr** [comment]
Yes, I will do the revision right now

**Comment by HedvigS** [comment]
> My grammar sketch on Hueyapan Nahuatl (Hansen 2017:166) is cited for "Morelos Nahuatl" having a copula verb with nominal predicates. But what I say on the cited page is the opposite, that the particle ka is _not_ a copula verb, that it is not a verb, but a particle that is optionally used to signal that the following noun is a predicate (a kind of focus construction). Nahuatl (also Tetelcingo Nahuatl, and all other Nahua varieties that I know of) notoriously lack copula verbs with nominal predicates.

Just to be clear, our definition of a copula here may result in this particle still qualifying. Please see. https://github.com/grambank/Grambank/wiki/GB117

**Comment by mariana-pr** [comment]
I've read both the wiki and the page in question, and I do not think it qualifies as a copula. It would probably be best described in terms of focus marking, as Maunus has suggested. From what I understand, its use is not restricted, but optional, which are not the same thing (the wiki says that restricted use should still be coded as 1).  Lots of languages with zero copula have similar things as well, like mapudungun, which was coded 0 for this feature.

**Comment by jaimerafaelms** [comment]
Upon further discussion with @mariana-pr we think it is best to leave it as 1, although it doesn’t coincide with the author's notion of copula. Feature GB117 asks for an element that licenses nominal predicates; it doesn't need to have the morphosyntactic behavior of a verb (it can even be a affix or clitic), nor it needs to be obligatory (in this case, particle **_ka_** with this function might be considered to be restricted to focused contexts). Grambank's definition allows what could be called "non-verbal copulas".

**Comment by Maunus** [comment]
Then I think you should not cite me as the source, since the page in
question specifically says the opposite.
I also have to say I think it is not particularly good practice to
reanalyze sources in this way.

ons. 29. nov. 2023 20.31 skrev jaimerafaelms ***@***.***>:

**Comment by Maunus** [comment]
Specifically there is no evidence that I am aware of that suggests that ka
"licenses nominal predicates", or any nahuatl grammarians that have argued
that it does in other varieties. Rather nahuatl has been argued to be
omnipredicative, meaning that all nouns are predicates that need no
licensing...

Ka is optional in all contexts also focused ones, and it is also used with
non nominal predicates.

If you absolutely want Nahuatl to have a copula a better candidate would be
the fact that nominal predicates take a locative verb that inflects for TAM
in non-present tense. Some scholars argue this is a copula.

ons. 29. nov. 2023 20.38 skrev Magnus Pharao Hansen ***@***.***

**Comment by mariana-pr** [comment]
@Maunus  I understand and, as I said previously, I do feel that it is similar to, for example, mapudungun, which was coded 0 for this feature (and I agree with that). In any case, no matter the coding I would write in the comment section what you have said, so that your stance on this is clearly stated, given that you are the referenced source. Some (most) categories are hard to define in a way that is coherent with all languages, and it is important that Grambank is at least internally coherent with a given definition for all features. Sometimes this does not coincide with the grammar's view on the same topic, which is obviously challenging. I will tag the patreons of this feature so that we can discuss this further.

**Comment by mariana-pr** [comment]
@HedvigS I am unable to tag or assign Jeremy and Jay, could you do it, please?

**Comment by SimonGreenhill** [comment]
@JeremyCollinsMPI @Jaylatarche can you look at this please?

**Comment by HedvigS** [comment]
> Then I think you should not cite me as the source, since the page in question specifically says the opposite. I also have to say I think it is not particularly good practice to reanalyze sources in this way. ons. 29. nov. 2023 20.31 skrev jaimerafaelms ***@***.***>:

We understand your concern. At times we find ourselves in the tricky position of having to re-analysing data and language phenomena in grammars, sometimes arriving at different categorisation and labels than the authors themselves used. We do not impose our cross-linguistic concepts on any language-specific description project, we think it's very important that the two are kept apart. Our categories are purely our own, we don't think that our labels and definitions have any universal application outside of our project. This does lead to discrepancies sometimes. All we do in such cases is follow our guidelines and try and do as consistent coding as possible over the languages in our dataset. For example, we have a feature [GB120 Can aspect be marked by an inflecting word (‘auxiliary verb’)?](https://github.com/grambank/Grambank/wiki/GB120) which has been coded 1 for markers that are not described as "auxiliary verbs" by grammar authors but for example "aspectual pronouns" etc. We use what information there is inside the grammars, also beyond strictly just repeating the particular labels that grammar-authors use. We look at the description of the function, its use, what other functions it has and if any of those mean that it is not dedicated enough to the function we're seeking to code for, how obligatory it is etc. We do this by reading the description by the author and by looking at examples. If we are not able to determine clearly what a construction is doing, we sometimes find ourselves coding "?" even when the grammar writer has provided a label.

It is true that your publication says that this marker is not a copula verb, and we appreciate you getting in touch. This feature does cover phenomena outside of strictly only "copula verbs", it essentially is targeted at any phenomena that is not just a plain juxta-position of two NPs. We are interested here in finding out given our grambank-diagnostics if this qualifies as a 1 for GB117.

I'd like to know more about the focus function of this marker. For example, does this marker occur as a focus marker outside of the nominal predication constructions? Knowing more about this would help us in determining the value for GB117, it would help out our feature patrons (final arbitrators of GB117) to proceed.

**Comment by HedvigS** [comment]
Hello again everyone @Maunus @mariana-pr @JeremyCollinsMPI @Jaylatarche .

This is a tricky case. The definition of a copula in our Grambank questionnaire is not the same as the specific work by @Maunus . We have had cases like this before, and the way we typically proceed is that we code as our project-internal categories dictate and then make a note how the definitions and terminology varies.

In this case, I think we need to know more about the focus function of this marker to proceed, like I said earlier. Until then, I suggest that we mark this data-point as "?".

**Comment by Maunus** [comment]
Ok, I think this is the best solution:
Put 1. Because: even though I don't write it explicitly in the chapter, Hueyapan Nahuatl does use the existential verb as copula in non-present tenses for example (yehwa oyiya tlahtoani "he was the governor", where oyiya is the imperfect tense existential/locative verb), which I think means it qualifies your criterion though I would probably choose an analysis that says that this is only because nominal predicates can't take T/A/M inflection.

**Comment by HedvigS** [comment]
> Ok, I think this is the best solution: Put 1. Because: even though I don't write it explicitly in the chapter, Hueyapan Nahuatl does use the existential verb as copula in non-present tenses for example (yehwa oyiya tlahtoani "he was the governor", where oyiya is the imperfect tense existential/locative verb), which I think means it qualifies your criterion though I would probably choose an analysis that says that this is only because nominal predicates can't take T/A/M inflection.

That makes sense to me. It is tricky when there are different definitions of concepts. I want you to know that we really appreciate that you reached out to us and that we had this conversation, this kind of interaction is very valuable to us and we are very grateful for it.
