### ISSUE TITLE
python cldfzenodo example

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#56]
@xrotwang or @johenglisch could you add a code snippet example here for how to use the python package cldfzenodo to fetch Grambank v1.0.3?

https://github.com/grambank/grambank/wiki/Fetching-and-analysing-Grambank-data-with-R#python-package-cldfzenodo

Thank you.

**Comment by xrotwang** [comment]
See https://github.com/grambank/grambank/wiki/Fetching-and-analysing-Grambank-data-with-R#python-package-cldfzenodo
