### ISSUE TITLE
English and Swedish agreement queries 

### ISSUE THREAD

**Issue by OlenaShcherbakova** [grambank/grambank#59]
1) If wanted to double check the English (stan1293) presence of adjective agreement in number for Feature GB184: Can an adnominal property word agree with the noun in number?

I didn't have a chance to check the source myself ([Huddleston and Pullum 2002](https://grambank.clld.org/sources/gHuddlestonPullumEnglish): 349-354), but I found it unexpected that adjectives are coded as agreeing with nouns in number.

2) I also wanted to double check the Swedish (swed1254) absence of article agreement in number GB186: Can an article agree with the noun in number? It could be that I misunderstand the feature, but I assumed that if different articles are used for singular nouns and plural ones, we would have presence of agreement there.

**Comment by HedvigS** [comment]
> 1. If wanted to double check the English (stan1293) presence of adjective agreement in number for Feature GB184: Can an adnominal property word agree with the noun in number?
> 
> I didn't have a chance to check the source myself ([Huddleston and Pullum 2002](https://grambank.clld.org/sources/gHuddlestonPullumEnglish): 349-354), but I found it unexpected that adjectives are coded as agreeing with nouns in number.

English has been checked a few times by different people, but never too much. Let's ask @JanisReimringer if he has time. It might be a confusion between articles and demonstratives (the - these).

> 2. I also wanted to double check the Swedish (swed1254) absence of article agreement in number GB186: Can an article agree with the noun in number? It could be that I misunderstand the feature, but I assumed that if different articles are used for singular nouns and plural ones, we would have presence of agreement there.

Swedish we had rechecked by a non-native speaker not too long ago, to make sure it was treated fairly from only the sources. I'm a little bit surprised by that analysis as well, there is indeed difference in definite articles for number.

@JanisReimringer would you want to recheck the swedish source too?

**Comment by HedvigS** [comment]
This might already be solved in the conflict coding after dumping of grambank v1.0 by the way, I'll check that now.

**Comment by HedvigS** [comment]
Yep, for the swedish this was already solved in the conflict coding (i.e. GB186 is coded 1). It just isn't reflected in the cldf-data yet because there hasn't been a rendering since v10. For when Grambank v2.0 is to be released, please ask RG :).

For English though, @JanisReimringer can you check what could cause GB184 to be 1 in Huddleston & Pullum (2002:349-354)?

**Comment by JanisReimringer** [comment]
> Yep, for the swedish this was already solved in the conflict coding (i.e. GB186 is coded 1). It just isn't reflected in the cldf-data yet because there hasn't been a rendering since v10. For when Grambank v2.0 is to be released, please ask RG :).
> 
> For English though, @JanisReimringer can you check what could cause GB184 to be 1 in Huddleston & Pullum (2002:349-354)?

Of course, I’m on it! :)

**Comment by JanisReimringer** [comment]
> Yep, for the swedish this was already solved in the conflict coding (i.e. GB186 is coded 1). It just isn't reflected in the cldf-data yet because there hasn't been a rendering since v10. For when Grambank v2.0 is to be released, please ask RG :).
> 
> For English though, @JanisReimringer can you check what could cause GB184 to be 1 in Huddleston & Pullum (2002:349-354)?

So what I gather from reading the referecend pages is that some adjectives, such as "countless" and "numerous", belong to the group of dependents that only select plural nouns (Huddleston & Pullum (2002:353)). So maybe that was counted towards agreement of an adnominal property word with a noun in number?

At the same time, Huddleston & Pullum (2002:528) state that adjectives do not inflect for number (as expected). There is no statement or example saying that adjective and noun can agree in number. I guess I can change the coding to 0?

**Comment by HedvigS** [comment]
> > Yep, for the swedish this was already solved in the conflict coding (i.e. GB186 is coded 1). It just isn't reflected in the cldf-data yet because there hasn't been a rendering since v10. For when Grambank v2.0 is to be released, please ask RG :).
> > For English though, @JanisReimringer can you check what could cause GB184 to be 1 in Huddleston & Pullum (2002:349-354)?
> 
> So what I gather from reading the referecend pages is that some adjectives, such as "countless" and "numerous", belong to the group of dependents that only select plural nouns (Huddleston & Pullum (2002:353)). So maybe that was counted towards agreement of an adnominal property word with a noun in number?
> 
> At the same time, Huddleston & Pullum (2002:528) state that adjectives do not inflect for number (as expected). There is no statement or example saying that adjective and noun can agree in number. I guess I can change the coding to 0?

Aha, I see. That doesn't seem enough. Let's change that to 0 please.

**Comment by JanisReimringer** [comment]
> > > Yep, for the swedish this was already solved in the conflict coding (i.e. GB186 is coded 1). It just isn't reflected in the cldf-data yet because there hasn't been a rendering since v10. For when Grambank v2.0 is to be released, please ask RG :).
> > > For English though, @JanisReimringer can you check what could cause GB184 to be 1 in Huddleston & Pullum (2002:349-354)?
> > 
> > 
> > So what I gather from reading the referecend pages is that some adjectives, such as "countless" and "numerous", belong to the group of dependents that only select plural nouns (Huddleston & Pullum (2002:353)). So maybe that was counted towards agreement of an adnominal property word with a noun in number?
> > At the same time, Huddleston & Pullum (2002:528) state that adjectives do not inflect for number (as expected). There is no statement or example saying that adjective and noun can agree in number. I guess I can change the coding to 0?
> 
> Aha, I see. That doesn't seem enough. Let's change that to 0 please.

Done! :)
