### ISSUE TITLE
Updating feature names in text on wiki systematically

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#6]
There are a few things we need to do systematically to the Grambank wiki. For example, as patrons are now updating feature names (the question itself), we need to make sure that wherever it is being referring to elsewhere in the wiki this change applies. The[ list of all features](https://github.com/grambank/grambank/wiki/List-of-all-features) is an example of such a page.

Jakob and I have been getting some use out of cloning the wiki to our local machines and making searches and sometimes changes directly in the md files on our machines and committing them. The GitHub workflow isn't very well set-up for how to deal with PRs and committs to wikis as opposed to repos itself, so it's not super easy but it's more or less working.

We would appreciate some help if that is possible with some of these overall wiki changes, especially the syncing of feature names wherever they are mentioned. These would follow a neat pattern of "GBXXX .*\?", so hopefully it isn't too hard to implement.

Would you @xrotwang or @chrzyki be able to help here?

**Comment by xrotwang** [comment]
Ok, I find 224 cases for  "GBXXX .*?", where the parsed feature question would need changing. But there are several false positives in there, see attached.
[report.txt](https://github.com/grambank/grambank/files/5510948/report.txt)

**Comment by HedvigS** [comment]
Thanks @xrotwang . 

Looking through the report file now. I wonder why is it finding the procedures sections?

**Comment by HedvigS** [comment]
@jlesg I think you want to look at the file Robert attached above.

**Comment by xrotwang** [comment]
Well, the regex was `GB[0-9]{3}[^?]?` - so GBXXX up to the next `?`. When excluding `.` in the supposed feature question, I get about 30 cases less.
[report.txt](https://github.com/grambank/grambank/files/5511214/report.txt)

**Comment by jlesg** [comment]
This is very helpful! It's on my to-do list to fix these. Thank you, @xrotwang and @HedvigS :)

**Comment by jlesg** [comment]
Made the necessary fixes. I'll close this for now, but I think it'd be good to run this again before the final dump of the wiki. I'll make a note of it.
