### ISSUE TITLE
Potential systematic coding problem: GB329

### ISSUE THREAD

**Issue by JuergenBohnemeyer** [grambank/grambank#61]
Internally headed relative clauses (IHRCs) are not known to occur in European languages. Therefore, I found it suspicious that several European languages (Catalan, Corsican, Slovenian) are coded as having IHRCs. So I checked the cited sources and found that the coder(s) had mistaken headless relative clauses for IHRCs in all three cases. 

I have not checked more than the three datapoints mentioned above, but my concern is that this may be a more systematic problem. In none of the cases in question does the source actually mention IHRCs, so clearly, it appears that the problem was that the coder incorrectly assumed that headless RCs are IHRCs. 

I think it would be advisable to either audit all datapoints of GB329 or check with the coders, determine which of them (if any) may have failed to appreciate the difference between IHRCs and headless RCs, and review all datapoints for which those coders were responsible.

Headless RCs and IHRCs are similar and thus confusable to non-specialists. Both involve nominalized clauses which are used non-attributively, unlike "classic" RCs. The difference is that headless RCs involve a gap, which may or may not be replaced by an indefinite pro-form, whereas IHRCs contain no gap. IHRCs are interpreted as implicit modifiers of one of their arguments - but this becomes clear only in the context of the matrix clause.

Another difference is that IHRCs are relatively rare in the languages of the world, whereas headless RCs are to my knowledge not. I would in fact venture the hypothesis that any language that has some form of finite RCs also has some strategy for forming headless RCs.

Regarding my expertise, I must admit that I have not worked much on clause combination in the last 25 years (other than vicariously through advising students and reviewing other researcher's work). My expertise comes primarily from studying clause combination in Mayan and typologically in the 1990s.

**Comment by jlesg** [comment]
Dear Jürgen,
Thank you for brining this up! You're absolutely right that there are some 'suspicious' datapoints (including apparently some I coded myself a long while ago). We'll need to check this feature in more detail.
All the best,
Jakob

**Comment by HedvigS** [comment]
> Dear Jürgen,
> Thank you for brining this up! You're absolutely right that there are some 'suspicious' datapoints (including apparently some I coded myself a long while ago). We'll need to check this feature in more detail.
> All the best,
> Jakob

@jlesg can you please help me to turn this into to-do-list items ?

**Comment by jlesg** [comment]
Done!
