### ISSUE TITLE
GB146: Is there a morphosyntactic distinction between predicates expressing controlled versus uncontrolled events or states?

### ISSUE THREAD

**Issue by leahpappas** [grambank/grambank#62]
I am struggling with coding this feature for many Austronesian languages that are typically considered to have symmetrical voice. Although this phenomenon occurs throughout the family, I'll use Kelabit to illustrate the issue I'm running into.

It seems like this feature targets special marking on uncontrolled events/states, but in many Western Austronesian languages, the opposite occurs. There is marking on the verb for controlled events (verbs with an agent) but zero-marking (or sometimes patient-voice marking) for uncontrolled events.

In Kelabit (kela1258; Hemming 2016:), this prefix is N- 'AV'. It marks that the verb has an actor

Uih    ne-nutun   [nibu       padey]
lSG   PFV-AV.try  AV.plant  rice
‘I tried to plant rice.’

It can serve a derivational function (2)

(2) _abet_ 'tie (n)' => _ngabet_ 'to tie smth (v)'

But it can also have a causative function (3), giving an actor to a verb that would not normally have one.

(3) _terem_ 'sink' => _nerem_ 'to sink smth'

Example (3) demonstrates, though, that verbs who do not have an agent remain unmarked. This isn't exclusive to uncontrolled states/events for animate subject. Stative verbs--which can describe any attributive property of a subject--are also unmarked.

So the issue here is that there is a difference in marking between controlled and uncontrolled subjects, but the marking is opposite from what is described in the wiki. The treatment of uncontrolled events/states with animate subjects are also no different from those with inanimate subjects. I've attached the Kelabit grammar below. I'm referencing p. 114-116, 224 and later examples, and I would love to know whether you would code something like this as "1."

[Hemmings_2016_Kelabit.pdf](https://github.com/grambank/grambank/files/15172093/Hemmings_2016_Kelabit.pdf)

**Comment by jlesg** [comment]
Hi Leah,
Thank you for this great question!
I'll say symmetrical voice systems do not count as a 1 for this feature, since they come too close to passives and causatives, which are excluded in the feature description. Please do make a comment about this where you encounter this situation, though.
I have to admit it's a tricky issue, so this decision is partly arbitrary, but nevertheless justifiable.
Please let me know if this is clear. Unless you have strong objections to this decision, I'll add it to the feature documentation. 
All the best,
Jakob

**Comment by leahpappas** [comment]
This is clear, and I don't have any strong objections to the decision, as I also feel there's a fundamental difference between what's going on in these Austronesian languages and the linguistic feature you're aiming for.

Adding this to the feature documentation page would be very helpful, though. When I was looking to see what others had done, there was no consensus on whether it was "1," "0," or "?".

Thank you for the help!
