### ISSUE TITLE
Predicative possession and alienable/inalienable possessive constructions in Jao

### ISSUE THREAD

**Issue by austronesianist** [grambank/grambank#64]
This issue is relevant to features GB252, GB253, GB254 on the encoding of predicative possession. The language under discussion is Jao/Jawe (jawe1237) and the source is my own field notes (Alexander Elias unpublished fieldnotes 2022). 

Outline of adnominal possession in Jao: There are two classes corresponding roughly to "alienable" and "inalienable". Inalienable nouns take a suffix to be possessed, which usually causes root alternations (/jat/ 'name' > /jale-n/ 'his/her name'). If a full NP possessor is used, the possessed root alternant is followed directly by the NP (/jale Alex/ 'Alex's name'). Alienable nouns are invariant, and a pronominal possessor is expressed with the dative preposition /li/ plus an enclitic drawn from a series used to mark the direct object of a verb in other constructions (/loto/ `car', /loto li=ek/ `his/her car', /loto li Alex/ 'Alex's car'). The morpheme /=ek/ `3SG.OBJ' is also used for the direct object of a transitive verb, as in /kaa=ek/ `hit him/her'. The word /li/ is also used to introduce complements of verbs like /pʰaᶮɟa/ `to ask (/pʰaᶮɟa li Alex/ `ask Alex', /pʰaᶮɟa li=ek/ `ask him/her'), so "dative" is a very appropriate gloss for this morpheme. 

Turning now to predicative possession, the main strategy is to use the existential predicate /pᵐʷa/ 'there is; to exist' plus whatever the appropriate possession strategy is for the noun in question. /pᵐʷa jale-n/ `S/he has a name' vs. /pᵐʷa loto li=ek/ `S/he has a car'. 

There is an additional strategy of predicative possession with slightly different semantics which uses "body part locatives". The word "hi-n" means "his/her hand", but it can also be used to mean "in his/her hand". The locative predicate is /jee/. The phrase /jee hi-n/ literally means "is in his/her hand", and is used for predicative possession, but only when the object is physically on one's person . Therefore, in order to express the English 'S/he has a book', Jao speakers could say either /pᵐʷa tii li=ek/ (A book exists to her.) or /jee hi-n tii/ (There is a book in her hand). The latter phrase, /jee hi-n tii/, could only be used if the book is physically on the person, but it could be in their pocket or backpack and need not be literally in their hand. The phrase /pᵐʷa tii li=ek/ is the only way of expressing that someone has a book at home, but it could also be used to express that someone has a book on their person. 

So my questions are: For GB252, the more restricted predicative possession strategy (possession on one's person) would perhaps qualify as a locative coded possessor. Should this be coded as 1 therefore, even if it is not the primary/default/most general possessive construction? 

For GB253, should the inalienable possessive predicate clause /pᵐʷa loto li=ek/ `S/he has a car be coded as a "dative-coded possessor"? Or should it be considered an "adnominal-coded possessor", since this is the strategy used to encode adnominal possession for these nouns in all cases?

**Comment by HedvigS** [comment]
I'm moving this to our meeting agenda.
