### ISSUE TITLE
Wordhood and derivational morphemes in Jao

### ISSUE THREAD

**Issue by austronesianist** [grambank/grambank#65]
This issue is relevant to features GB048, GB114, GB115, GB155, GB305, GB306 on the encoding of causatives, reflexives and agentives as bound morphology or free forms. The language under discussion is Jao/Jawe (jawe1237) and the source is my own field notes (Alexander Elias unpublished fieldnotes 2022). 

I am struggling to fit the behavior of a certain class of derivational morphemes in Jao into the free-bound continuum. Jao uses what I call in my head "derivational proclitics", productive morphemes like /po/ `verbalizer' (/pò ínternet/ `to surf the web', /pò tíi/ `to write = to make writing', /pe/ `reciprocal' (/pè nóᶮɟa/ `to see each other', /pè pò tíi/ `to write to each other, to correspond'), /pʰa/ `causative' (/pʰà cáuɣi/ `to cool something down'), /ka/ `agentive nominal' (/kà sómu/ `teacher'). A secondary stress always falls on each "proclitic", and main stress on the root. There may be lots of them and they have very compositional semantics: /kà pè pò páac/ <AGT RECIP VRB war> `combatants; those who make war on each other', /pʰà pè pò tíi/ <CAUS RECIP VRB write> `to make (people) write to each other'. Orthographically, they are written separately.  

Jao has a strict prohibition against all voiceless sounds within a unit which corresponds intuitively to the "phonological word" and which is also the domain which is footed together in stress assignment. The "words" **kasomu and **pʰapepotii would not well-formed in Jao, and the well-formed equivalents (applying the normal rules of intervocalic lenition) are [kájomu, pʰávewoɾìi] respectively. Based on intervocalic lenition and stress assignment, it is clear to me that /kà pè pò páac/ should be considered a unit larger than a phonological word.

Bound characteristics: (1) they cannot occur alone, there is no free word that looks like them, (2) they could be argued to be part of the stress domain of the main root, since they only can have secondary stress while the root can have primary (their stress depends on the stress of another morpheme in a way), (3) they combine with hosts of just one grammatical category (/po/ is only for verbalizing nouns), making them seem like affixes which are by definition bound

Free characteristics: (1) They are phonologically invariant (2) it could be argued that each one has its own stress domain, because feet are usually bimoraic in Jao, so each "derivational proclitic" is footed and stressed separately, like a small phonological word would be (there are no other examples of stressed monomoraic feet apart from short lexical words), (3) orthographically separate.  

There are clear examples of true affixal prefixes in Jao as well (which cause lenition and could receive a main stress). /kaa-/ `dyadic kinship prefix' > /paᵑgúu-n/ `his/her grandchild' > /káa-vaᵑgùu-n/ `pair of uncle and nephew/niece'. 

So the question for GB048, GB114, GB115, GB155 is whether or not these "derivational proclitics" like agentive /ka/, reciprocal/reflexive /pe/ and causative /pa, pha/ are to be considered as free or bound morphemes.

**Comment by HedvigS** [comment]
I'm moving this to our meetings rolling agenda.
