### ISSUE TITLE
GB400 - Russian is 0, but it should be 1

### ISSUE THREAD

**Issue by NereaMadariaga** [grambank/grambank#66]
Feature GB 400: Are all person categories neutralized in some voice, tense, aspect, mood and/or negation?
Language: Russian
It is marked as 0, but it should be 1, because, while person distinctions are preserved intact in non-past tenses, all **person** distinctions are completely neutralized in past tense (only gender and number are marked in the past). 
Any source that you already mention in the article will do (Wade, etc).

**Comment by HedvigS** [comment]
Thank you @NereaMadariaga . I'll assign someone to go over this.

**Comment by leahpappas** [comment]
Hi, I've confirmed that this should be coded as one since person distinctions are neutralized in past tense (Dunn & Khairov 2009:151, 252). I'll make the edit to the current coding.

**Comment by HedvigS** [comment]
Thank you @leahpappas !
