### ISSUE TITLE
updating wiki article content on website separately from CLDF full rendering

### ISSUE THREAD

**Issue by HedvigS** [grambank/grambank#7]
Hi @xrotwang 

As was discussed before, we want to push changes in grambank/grambank.wiki to the clld website separately from the full cldf rendering. We talked about this before. Is this going to be possible?

We're currently aiming at 13th of December as final date for all the wiki reviews to be finished.

In the meantime we've noticed some unfortunate things with the rendering of the content on some of the features as website content

- Links to general wiki articles don’t always work (e.g. ‘boundness’ in GB114)
- Tables don’t always render (e.g. GB026)
- ‘and’ in “Jay and Jeremy” has funny quotation marks

What can we do to help with this?

**Comment by xrotwang** [comment]
AFAIR what we discussed was including newer versions of the wiki into the CLDF data based on older versions of the data repository. And yes, that's possible. The website is always fed from a CLDF dataset which includes data **and** descriptions.

Regarding rendering problems: I'll have a look. Exact descriptions of the problems would be good, though. E.g. I cannot find a problem on https://grambank.clld.org/parameters/GB114 - in fact, I can't even find the word "boundness" on the page at all.

**Comment by xrotwang** [comment]
The table in GB026 seems to have been replaced in the meantime, see https://github.com/grambank/grambank/wiki/GB026

**Comment by HedvigS** [comment]
Okay, good. @alenawitzlack @tobiaskweber and @jlesg were the ones noticing discrepancies so I'll let them write more here if there's more to note.

**Comment by xrotwang** [comment]
The funny quotation marks are gone in the code (see https://github.com/clld/grambank/commit/3018a467a228b6b4f6250c32f692e002e847c17b#diff-81a3f3b4e2f5047ea03031a9d59779087ad1b5d2b14c21503365ae4632d52ce6) but the change hasn't been deployed yet.

**Comment by xrotwang** [comment]
Going through the articles on the website now may not be super helpful, considering there's still editing going on in the wiki. Better would be a review period **after** December 13 and **after** the latest changes have been pushed to the website.

**Comment by HedvigS** [comment]
We are reviewing the articles based on the wiki page, we're just looking at the way things are rendered on the website in general. The way tables are made in the wiki articles shouldn't change much after the 13th for example, so the same issues should remain I believe.

**Comment by HedvigS** [comment]
That's at least my understanding, that @jlesg and the others were raising more general notes with specific examples.

**Comment by jlesg** [comment]
Hey @xrotwang and @HedvigS ,

Thank you for taking the time for bringing this up and discussing this.

One of the things we discussed during the meeting was that we're not entirely sure which problems are
1) because of an earlier version of the wiki articles on GitHub, and
2) which problems may have to do with the push to the website.

I'd like to have a brief look at the website articles next week. Possibly most issues are due to 1), so they may no longer be issues.

I'll come back with some exact descriptions of problems later, if they're still around!

All the best,

Jakob

**Comment by jlesg** [comment]
I haven't been able to have a good look at these yet.

Let's hold off the push to the website until we have agreed that the wiki is fairly final, some point after the 13th. Like @xrotwang said. It's possible that not everything will be finished by the 13th. Some patrons have had unusually busy schedules the last few weeks.

**Comment by HedvigS** [comment]
@xrotwang just letting you know we're at the last stage of finalising wiki now, I'll let you know when it's ready for things to happen in this regard.

The patrons are currently making smaller changes to the feature question wording, which I believe means we also need to update the "gb20.txt" document which the CLDF rendering uses. What is the easiest way of making that link?

**Comment by xrotwang** [comment]
Info that can be read from the wiki is taken from there. So no need to sync respective fields in `gb20.txt`.

**Comment by HedvigS** [comment]
Okay, great. 

For the CLDF "parameters.csv" and the way the Feature "Name" is rendered there, that is taken from gb20.txt right?

**Comment by xrotwang** [comment]
Yes. Could be replaced with the wiki title, though.
